/**********************************************************************************************************************
 *  COPYRIGHT
 *  -------------------------------------------------------------------------------------------------------------------
 *  \verbatim
 *
 *                 This software is copyright protected and proprietary to Vector Informatik GmbH.
 *                 Vector Informatik GmbH grants to you only those rights as set out in the license conditions.
 *                 All other rights remain with Vector Informatik GmbH.
 *  \endverbatim
 *  -------------------------------------------------------------------------------------------------------------------
 *  LICENSE
 *  -------------------------------------------------------------------------------------------------------------------
 *            Module: Os
 *           Program: MSR_Vector_SLP4
 *          Customer: Aptiv (China) Technology Company Ltd.
 *       Expiry Date: Not restricted
 *  Ordered Derivat.: Aurix 2G/TC397 B-Step
 *    License Scope : The usage is restricted to CBD1900078_D01
 *
 *  -------------------------------------------------------------------------------------------------------------------
 *  FILE DESCRIPTION
 *  -------------------------------------------------------------------------------------------------------------------
 *              File: Os_Hal_Entry_Lcfg.c
 *   Generation Time: 2024-01-08 16:27:31
 *           Project: Bsw_Project - Version 1.0
 *          Delivery: CBD1900078_D01
 *      Tool Version: DaVinci Configurator (beta) 5.18.42 SP2
 *
 *
 *********************************************************************************************************************/

/**********************************************************************************************************************
 ! BETA VERSION                                                                                                       !
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 ! This version of DaVinci Configurator Pro and/or the related Basic Software Package is BETA software.               !
 ! BETA Software is basically operable, but not sufficiently tested, verified and/or qualified for use in series      !
 ! production and/or in vehicles operating on public or non-public roads.                                             !
 ! In particular, without limitation, BETA Software may cause unpredictable ECU behavior, may not provide all         !
 ! functions necessary for use in series production and/or may not comply with quality requirements which are         !
 ! necessary according to the state of the art. BETA Software must not be used in series production.                  !
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
**********************************************************************************************************************/

/* PRQA S 0777, 0779, 0828 EOF */ /* MD_MSR_Rule5.1, MD_MSR_Rule5.2, MD_MSR_Dir1.1 */

#define OS_HAL_ENTRY_LCFG_SOURCE

/**********************************************************************************************************************
 *  INCLUDES
 *********************************************************************************************************************/

/* AUTOSAR includes */
#include "Std_Types.h"

/* Os module declarations */
#include "Os_Hal_Entry_Cfg.h"
#include "Os_Hal_Entry_Lcfg.h"
#include "Os_Hal_Entry.h"

/* Os kernel module dependencies */
#include "Os_Isr_Lcfg.h"
#include "Os.h"

/* Os hal dependencies */
#include "Os_Hal_Cfg.h"
#include "Os_Hal_Core_Lcfg.h"
#include "Os_Hal_Interrupt_Cfg.h"
#include "Os_Hal_Trap.h"


/**********************************************************************************************************************
 *  LOCAL CONSTANT MACROS
 *********************************************************************************************************************/

/**********************************************************************************************************************
 *  LOCAL FUNCTION MACROS
 *********************************************************************************************************************/

/**********************************************************************************************************************
 *  LOCAL DATA TYPES AND STRUCTURES
 *********************************************************************************************************************/

/**********************************************************************************************************************
 *  LOCAL DATA PROTOTYPES
 *********************************************************************************************************************/

/**********************************************************************************************************************
 *  GLOBAL DATA
 *********************************************************************************************************************/

/**********************************************************************************************************************
 *  GLOBAL CONSTANT DATA
 *********************************************************************************************************************/

/**********************************************************************************************************************
 *  EXCEPTION VECTOR TABLE CORE 0
 *********************************************************************************************************************/

#define OS_START_SEC_EXCVEC_CORE0_CODE
#include "Os_MemMap_OsSections.h" /* PRQA S 5087 */ /* MD_MSR_MemMap */

Os_Hal_UnhandledTrapEntry(0, 0)
Os_Hal_UnhandledTrapEntry(0, 1)
Os_Hal_UnhandledTrapEntry(0, 2)
Os_Hal_UnhandledTrapEntry(0, 3)
Os_Hal_UnhandledTrapEntry(0, 4)
Os_Hal_UnhandledTrapEntry(0, 5)
Os_Hal_UnhandledTrapEntry(0, 6)
Os_Hal_UnhandledTrapEntry(0, 7)

#define OS_STOP_SEC_EXCVEC_CORE0_CODE
#include "Os_MemMap_OsSections.h" /* PRQA S 5087 */ /* MD_MSR_MemMap */


/**********************************************************************************************************************
 *  INTERRUPT VECTOR TABLE CORE 0
 *********************************************************************************************************************/

#define OS_START_SEC_INTVEC_CORE0_CODE
#include "Os_MemMap_OsSections.h" /* PRQA S 5087 */ /* MD_MSR_MemMap */

Os_Hal_UnhandledInterruptEntry(0, 0)
Os_Hal_UnhandledInterruptEntry(0, 1)
Os_Hal_UnhandledInterruptEntry(0, 2)
Os_Hal_UnhandledInterruptEntry(0, 3)
Os_Hal_UnhandledInterruptEntry(0, 4)
Os_Hal_UnhandledInterruptEntry(0, 5)
Os_Hal_UnhandledInterruptEntry(0, 6)
Os_Hal_UnhandledInterruptEntry(0, 7)
Os_Hal_UnhandledInterruptEntry(0, 8)
Os_Hal_UnhandledInterruptEntry(0, 9)
Os_Hal_UnhandledInterruptEntry(0, 10)
Os_Hal_UnhandledInterruptEntry(0, 11)
Os_Hal_Cat2InterruptEntry(0, 12, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_CounterIsr_SystemTimer0)
Os_Hal_UnhandledInterruptEntry(0, 13)
Os_Hal_UnhandledInterruptEntry(0, 14)
Os_Hal_UnhandledInterruptEntry(0, 15)
Os_Hal_UnhandledInterruptEntry(0, 16)
Os_Hal_UnhandledInterruptEntry(0, 17)
Os_Hal_Cat2InterruptEntry(0, 18, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_XSignalIsr_OsCore0)
Os_Hal_UnhandledInterruptEntry(0, 19)
Os_Hal_UnhandledInterruptEntry(0, 20)
Os_Hal_UnhandledInterruptEntry(0, 21)
Os_Hal_Cat2InterruptEntry(0, 22, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_ADC0SR0_ISR)
Os_Hal_Cat2InterruptEntry(0, 23, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_ADC1SR0_ISR)
Os_Hal_Cat2InterruptEntry(0, 24, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_ADC2SR0_ISR)
Os_Hal_Cat2InterruptEntry(0, 25, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_ADC3SR0_ISR)
Os_Hal_Cat2InterruptEntry(0, 26, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_DMACH0SR_ISR)
Os_Hal_Cat2InterruptEntry(0, 27, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_DMACH3SR_ISR)
Os_Hal_Cat2InterruptEntry(0, 28, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_DMACH4SR_ISR)
Os_Hal_Cat2InterruptEntry(0, 29, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_DMACH5SR_ISR)
Os_Hal_Cat2InterruptEntry(0, 30, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_DMACH6SR_ISR)
Os_Hal_Cat2InterruptEntry(0, 31, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_DMACH7SR_ISR)
Os_Hal_Cat2InterruptEntry(0, 32, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_DMACH8SR_ISR)
Os_Hal_Cat2InterruptEntry(0, 33, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_DMACH9SR_ISR)
Os_Hal_UnhandledInterruptEntry(0, 34)
Os_Hal_UnhandledInterruptEntry(0, 35)
Os_Hal_UnhandledInterruptEntry(0, 36)
Os_Hal_UnhandledInterruptEntry(0, 37)
Os_Hal_UnhandledInterruptEntry(0, 38)
Os_Hal_Cat2InterruptEntry(0, 39, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_QSPI2ERR_ISR)
Os_Hal_Cat2InterruptEntry(0, 40, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_QSPI2PT_ISR)
Os_Hal_Cat2InterruptEntry(0, 41, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_QSPI3ERR_ISR)
Os_Hal_Cat2InterruptEntry(0, 42, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_QSPI3PT_ISR)
Os_Hal_Cat2InterruptEntry(0, 43, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_QSPI1ERR_ISR)
Os_Hal_Cat2InterruptEntry(0, 44, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_QSPI1PT_ISR)
Os_Hal_Cat2InterruptEntry(0, 45, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_QSPI0ERR_ISR)
Os_Hal_Cat2InterruptEntry(0, 46, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_QSPI0PT_ISR)
Os_Hal_Cat2InterruptEntry(0, 47, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_DMAERR0SR_ISR)
Os_Hal_Cat2InterruptEntry(0, 48, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_ADC8SR0_ISR)
Os_Hal_Cat2InterruptEntry(0, 49, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_CanIsr_5)
Os_Hal_UnhandledInterruptEntry(0, 50)
Os_Hal_UnhandledInterruptEntry(0, 51)
Os_Hal_UnhandledInterruptEntry(0, 52)
Os_Hal_UnhandledInterruptEntry(0, 53)
Os_Hal_UnhandledInterruptEntry(0, 54)
Os_Hal_Cat2InterruptEntry(0, 55, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_GTMATOM0SR0_ISR)
Os_Hal_Cat2InterruptEntry(0, 56, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_GTMATOM1SR0_ISR)
Os_Hal_Cat2InterruptEntry(0, 57, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_GTMATOM2SR0_ISR)
Os_Hal_Cat2InterruptEntry(0, 58, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_GTMATOM4SR0_ISR)
Os_Hal_Cat2InterruptEntry(0, 59, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_GTMTIM2SR3_ISR)
Os_Hal_Cat2InterruptEntry(0, 60, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_GTMTIM2SR5_ISR)
Os_Hal_Cat2InterruptEntry(0, 61, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_GTMTOM0SR0_ISR)
Os_Hal_Cat2InterruptEntry(0, 62, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_GTMTOM0SR1_ISR)
Os_Hal_Cat2InterruptEntry(0, 63, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_GTMTOM0SR2_ISR)
Os_Hal_Cat2InterruptEntry(0, 64, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_GTMTOM0SR3_ISR)
Os_Hal_UnhandledInterruptEntry(0, 65)
Os_Hal_UnhandledInterruptEntry(0, 66)
Os_Hal_UnhandledInterruptEntry(0, 67)
Os_Hal_UnhandledInterruptEntry(0, 68)
Os_Hal_Cat2InterruptEntry(0, 69, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_CanIsr_4)
Os_Hal_UnhandledInterruptEntry(0, 70)
Os_Hal_UnhandledInterruptEntry(0, 71)
Os_Hal_UnhandledInterruptEntry(0, 72)
Os_Hal_UnhandledInterruptEntry(0, 73)
Os_Hal_UnhandledInterruptEntry(0, 74)
Os_Hal_UnhandledInterruptEntry(0, 75)
Os_Hal_UnhandledInterruptEntry(0, 76)
Os_Hal_UnhandledInterruptEntry(0, 77)
Os_Hal_UnhandledInterruptEntry(0, 78)
Os_Hal_UnhandledInterruptEntry(0, 79)
Os_Hal_UnhandledInterruptEntry(0, 80)
Os_Hal_UnhandledInterruptEntry(0, 81)
Os_Hal_UnhandledInterruptEntry(0, 82)
Os_Hal_UnhandledInterruptEntry(0, 83)
Os_Hal_UnhandledInterruptEntry(0, 84)
Os_Hal_UnhandledInterruptEntry(0, 85)
Os_Hal_UnhandledInterruptEntry(0, 86)
Os_Hal_UnhandledInterruptEntry(0, 87)
Os_Hal_UnhandledInterruptEntry(0, 88)
Os_Hal_UnhandledInterruptEntry(0, 89)
Os_Hal_UnhandledInterruptEntry(0, 90)
Os_Hal_UnhandledInterruptEntry(0, 91)
Os_Hal_UnhandledInterruptEntry(0, 92)
Os_Hal_UnhandledInterruptEntry(0, 93)
Os_Hal_UnhandledInterruptEntry(0, 94)
Os_Hal_UnhandledInterruptEntry(0, 95)
Os_Hal_UnhandledInterruptEntry(0, 96)
Os_Hal_UnhandledInterruptEntry(0, 97)
Os_Hal_UnhandledInterruptEntry(0, 98)
Os_Hal_UnhandledInterruptEntry(0, 99)
Os_Hal_UnhandledInterruptEntry(0, 100)
Os_Hal_UnhandledInterruptEntry(0, 101)
Os_Hal_UnhandledInterruptEntry(0, 102)
Os_Hal_UnhandledInterruptEntry(0, 103)
Os_Hal_UnhandledInterruptEntry(0, 104)
Os_Hal_UnhandledInterruptEntry(0, 105)
Os_Hal_UnhandledInterruptEntry(0, 106)
Os_Hal_UnhandledInterruptEntry(0, 107)
Os_Hal_UnhandledInterruptEntry(0, 108)
Os_Hal_UnhandledInterruptEntry(0, 109)
Os_Hal_UnhandledInterruptEntry(0, 110)
Os_Hal_UnhandledInterruptEntry(0, 111)
Os_Hal_UnhandledInterruptEntry(0, 112)
Os_Hal_UnhandledInterruptEntry(0, 113)
Os_Hal_UnhandledInterruptEntry(0, 114)
Os_Hal_UnhandledInterruptEntry(0, 115)
Os_Hal_UnhandledInterruptEntry(0, 116)
Os_Hal_UnhandledInterruptEntry(0, 117)
Os_Hal_UnhandledInterruptEntry(0, 118)
Os_Hal_UnhandledInterruptEntry(0, 119)
Os_Hal_UnhandledInterruptEntry(0, 120)
Os_Hal_UnhandledInterruptEntry(0, 121)
Os_Hal_UnhandledInterruptEntry(0, 122)
Os_Hal_UnhandledInterruptEntry(0, 123)
Os_Hal_UnhandledInterruptEntry(0, 124)
Os_Hal_UnhandledInterruptEntry(0, 125)
Os_Hal_UnhandledInterruptEntry(0, 126)
Os_Hal_UnhandledInterruptEntry(0, 127)
Os_Hal_UnhandledInterruptEntry(0, 128)
Os_Hal_UnhandledInterruptEntry(0, 129)
Os_Hal_UnhandledInterruptEntry(0, 130)
Os_Hal_UnhandledInterruptEntry(0, 131)
Os_Hal_UnhandledInterruptEntry(0, 132)
Os_Hal_UnhandledInterruptEntry(0, 133)
Os_Hal_UnhandledInterruptEntry(0, 134)
Os_Hal_UnhandledInterruptEntry(0, 135)
Os_Hal_UnhandledInterruptEntry(0, 136)
Os_Hal_UnhandledInterruptEntry(0, 137)
Os_Hal_UnhandledInterruptEntry(0, 138)
Os_Hal_UnhandledInterruptEntry(0, 139)
Os_Hal_UnhandledInterruptEntry(0, 140)
Os_Hal_UnhandledInterruptEntry(0, 141)
Os_Hal_UnhandledInterruptEntry(0, 142)
Os_Hal_UnhandledInterruptEntry(0, 143)
Os_Hal_UnhandledInterruptEntry(0, 144)
Os_Hal_UnhandledInterruptEntry(0, 145)
Os_Hal_UnhandledInterruptEntry(0, 146)
Os_Hal_UnhandledInterruptEntry(0, 147)
Os_Hal_UnhandledInterruptEntry(0, 148)
Os_Hal_UnhandledInterruptEntry(0, 149)
Os_Hal_UnhandledInterruptEntry(0, 150)
Os_Hal_UnhandledInterruptEntry(0, 151)
Os_Hal_UnhandledInterruptEntry(0, 152)
Os_Hal_UnhandledInterruptEntry(0, 153)
Os_Hal_UnhandledInterruptEntry(0, 154)
Os_Hal_UnhandledInterruptEntry(0, 155)
Os_Hal_UnhandledInterruptEntry(0, 156)
Os_Hal_UnhandledInterruptEntry(0, 157)
Os_Hal_UnhandledInterruptEntry(0, 158)
Os_Hal_UnhandledInterruptEntry(0, 159)
Os_Hal_UnhandledInterruptEntry(0, 160)
Os_Hal_UnhandledInterruptEntry(0, 161)
Os_Hal_UnhandledInterruptEntry(0, 162)
Os_Hal_UnhandledInterruptEntry(0, 163)
Os_Hal_UnhandledInterruptEntry(0, 164)
Os_Hal_UnhandledInterruptEntry(0, 165)
Os_Hal_UnhandledInterruptEntry(0, 166)
Os_Hal_UnhandledInterruptEntry(0, 167)
Os_Hal_UnhandledInterruptEntry(0, 168)
Os_Hal_UnhandledInterruptEntry(0, 169)
Os_Hal_UnhandledInterruptEntry(0, 170)
Os_Hal_UnhandledInterruptEntry(0, 171)
Os_Hal_UnhandledInterruptEntry(0, 172)
Os_Hal_UnhandledInterruptEntry(0, 173)
Os_Hal_UnhandledInterruptEntry(0, 174)
Os_Hal_UnhandledInterruptEntry(0, 175)
Os_Hal_UnhandledInterruptEntry(0, 176)
Os_Hal_UnhandledInterruptEntry(0, 177)
Os_Hal_UnhandledInterruptEntry(0, 178)
Os_Hal_UnhandledInterruptEntry(0, 179)
Os_Hal_UnhandledInterruptEntry(0, 180)
Os_Hal_UnhandledInterruptEntry(0, 181)
Os_Hal_UnhandledInterruptEntry(0, 182)
Os_Hal_UnhandledInterruptEntry(0, 183)
Os_Hal_UnhandledInterruptEntry(0, 184)
Os_Hal_UnhandledInterruptEntry(0, 185)
Os_Hal_UnhandledInterruptEntry(0, 186)
Os_Hal_UnhandledInterruptEntry(0, 187)
Os_Hal_UnhandledInterruptEntry(0, 188)
Os_Hal_UnhandledInterruptEntry(0, 189)
Os_Hal_UnhandledInterruptEntry(0, 190)
Os_Hal_UnhandledInterruptEntry(0, 191)
Os_Hal_UnhandledInterruptEntry(0, 192)
Os_Hal_UnhandledInterruptEntry(0, 193)
Os_Hal_UnhandledInterruptEntry(0, 194)
Os_Hal_UnhandledInterruptEntry(0, 195)
Os_Hal_UnhandledInterruptEntry(0, 196)
Os_Hal_UnhandledInterruptEntry(0, 197)
Os_Hal_UnhandledInterruptEntry(0, 198)
Os_Hal_UnhandledInterruptEntry(0, 199)
Os_Hal_UnhandledInterruptEntry(0, 200)
Os_Hal_UnhandledInterruptEntry(0, 201)
Os_Hal_UnhandledInterruptEntry(0, 202)
Os_Hal_UnhandledInterruptEntry(0, 203)
Os_Hal_UnhandledInterruptEntry(0, 204)
Os_Hal_UnhandledInterruptEntry(0, 205)
Os_Hal_UnhandledInterruptEntry(0, 206)
Os_Hal_UnhandledInterruptEntry(0, 207)
Os_Hal_UnhandledInterruptEntry(0, 208)
Os_Hal_UnhandledInterruptEntry(0, 209)
Os_Hal_UnhandledInterruptEntry(0, 210)
Os_Hal_UnhandledInterruptEntry(0, 211)
Os_Hal_UnhandledInterruptEntry(0, 212)
Os_Hal_UnhandledInterruptEntry(0, 213)
Os_Hal_UnhandledInterruptEntry(0, 214)
Os_Hal_UnhandledInterruptEntry(0, 215)
Os_Hal_UnhandledInterruptEntry(0, 216)
Os_Hal_UnhandledInterruptEntry(0, 217)
Os_Hal_UnhandledInterruptEntry(0, 218)
Os_Hal_UnhandledInterruptEntry(0, 219)
Os_Hal_UnhandledInterruptEntry(0, 220)
Os_Hal_UnhandledInterruptEntry(0, 221)
Os_Hal_UnhandledInterruptEntry(0, 222)
Os_Hal_UnhandledInterruptEntry(0, 223)
Os_Hal_UnhandledInterruptEntry(0, 224)
Os_Hal_UnhandledInterruptEntry(0, 225)
Os_Hal_UnhandledInterruptEntry(0, 226)
Os_Hal_UnhandledInterruptEntry(0, 227)
Os_Hal_UnhandledInterruptEntry(0, 228)
Os_Hal_UnhandledInterruptEntry(0, 229)
Os_Hal_UnhandledInterruptEntry(0, 230)
Os_Hal_UnhandledInterruptEntry(0, 231)
Os_Hal_UnhandledInterruptEntry(0, 232)
Os_Hal_UnhandledInterruptEntry(0, 233)
Os_Hal_UnhandledInterruptEntry(0, 234)
Os_Hal_UnhandledInterruptEntry(0, 235)
Os_Hal_UnhandledInterruptEntry(0, 236)
Os_Hal_UnhandledInterruptEntry(0, 237)
Os_Hal_UnhandledInterruptEntry(0, 238)
Os_Hal_UnhandledInterruptEntry(0, 239)
Os_Hal_UnhandledInterruptEntry(0, 240)
Os_Hal_UnhandledInterruptEntry(0, 241)
Os_Hal_UnhandledInterruptEntry(0, 242)
Os_Hal_UnhandledInterruptEntry(0, 243)
Os_Hal_UnhandledInterruptEntry(0, 244)
Os_Hal_UnhandledInterruptEntry(0, 245)
Os_Hal_UnhandledInterruptEntry(0, 246)
Os_Hal_UnhandledInterruptEntry(0, 247)
Os_Hal_UnhandledInterruptEntry(0, 248)
Os_Hal_UnhandledInterruptEntry(0, 249)
Os_Hal_UnhandledInterruptEntry(0, 250)
Os_Hal_UnhandledInterruptEntry(0, 251)
Os_Hal_UnhandledInterruptEntry(0, 252)
Os_Hal_UnhandledInterruptEntry(0, 253)
Os_Hal_UnhandledInterruptEntry(0, 254)
Os_Hal_UnhandledInterruptEntry(0, 255)

#define OS_STOP_SEC_INTVEC_CORE0_CODE
#include "Os_MemMap_OsSections.h" /* PRQA S 5087 */ /* MD_MSR_MemMap */


/**********************************************************************************************************************
 *  EXCEPTION VECTOR TABLE CORE 1
 *********************************************************************************************************************/

#define OS_START_SEC_EXCVEC_CORE1_CODE
#include "Os_MemMap_OsSections.h" /* PRQA S 5087 */ /* MD_MSR_MemMap */

Os_Hal_UnhandledTrapEntry(1, 0)
Os_Hal_UnhandledTrapEntry(1, 1)
Os_Hal_UnhandledTrapEntry(1, 2)
Os_Hal_UnhandledTrapEntry(1, 3)
Os_Hal_UnhandledTrapEntry(1, 4)
Os_Hal_UnhandledTrapEntry(1, 5)
Os_Hal_UnhandledTrapEntry(1, 6)
Os_Hal_UnhandledTrapEntry(1, 7)

#define OS_STOP_SEC_EXCVEC_CORE1_CODE
#include "Os_MemMap_OsSections.h" /* PRQA S 5087 */ /* MD_MSR_MemMap */


/**********************************************************************************************************************
 *  INTERRUPT VECTOR TABLE CORE 1
 *********************************************************************************************************************/

#define OS_START_SEC_INTVEC_CORE1_CODE
#include "Os_MemMap_OsSections.h" /* PRQA S 5087 */ /* MD_MSR_MemMap */

Os_Hal_UnhandledInterruptEntry(1, 0)
Os_Hal_UnhandledInterruptEntry(1, 1)
Os_Hal_UnhandledInterruptEntry(1, 2)
Os_Hal_UnhandledInterruptEntry(1, 3)
Os_Hal_UnhandledInterruptEntry(1, 4)
Os_Hal_UnhandledInterruptEntry(1, 5)
Os_Hal_UnhandledInterruptEntry(1, 6)
Os_Hal_UnhandledInterruptEntry(1, 7)
Os_Hal_UnhandledInterruptEntry(1, 8)
Os_Hal_UnhandledInterruptEntry(1, 9)
Os_Hal_UnhandledInterruptEntry(1, 10)
Os_Hal_UnhandledInterruptEntry(1, 11)
Os_Hal_UnhandledInterruptEntry(1, 12)
Os_Hal_UnhandledInterruptEntry(1, 13)
Os_Hal_UnhandledInterruptEntry(1, 14)
Os_Hal_UnhandledInterruptEntry(1, 15)
Os_Hal_UnhandledInterruptEntry(1, 16)
Os_Hal_UnhandledInterruptEntry(1, 17)
Os_Hal_Cat2InterruptEntry(1, 18, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_XSignalIsr_OsCore1)
Os_Hal_UnhandledInterruptEntry(1, 19)
Os_Hal_Cat2InterruptEntry(1, 20, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_CounterIsr_SystemTimer1)
Os_Hal_Cat2InterruptEntry(1, 21, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_CanIsr_0)
Os_Hal_UnhandledInterruptEntry(1, 22)
Os_Hal_UnhandledInterruptEntry(1, 23)
Os_Hal_UnhandledInterruptEntry(1, 24)
Os_Hal_UnhandledInterruptEntry(1, 25)
Os_Hal_UnhandledInterruptEntry(1, 26)
Os_Hal_UnhandledInterruptEntry(1, 27)
Os_Hal_UnhandledInterruptEntry(1, 28)
Os_Hal_UnhandledInterruptEntry(1, 29)
Os_Hal_UnhandledInterruptEntry(1, 30)
Os_Hal_UnhandledInterruptEntry(1, 31)
Os_Hal_UnhandledInterruptEntry(1, 32)
Os_Hal_UnhandledInterruptEntry(1, 33)
Os_Hal_UnhandledInterruptEntry(1, 34)
Os_Hal_UnhandledInterruptEntry(1, 35)
Os_Hal_UnhandledInterruptEntry(1, 36)
Os_Hal_UnhandledInterruptEntry(1, 37)
Os_Hal_UnhandledInterruptEntry(1, 38)
Os_Hal_UnhandledInterruptEntry(1, 39)
Os_Hal_UnhandledInterruptEntry(1, 40)
Os_Hal_UnhandledInterruptEntry(1, 41)
Os_Hal_UnhandledInterruptEntry(1, 42)
Os_Hal_UnhandledInterruptEntry(1, 43)
Os_Hal_UnhandledInterruptEntry(1, 44)
Os_Hal_UnhandledInterruptEntry(1, 45)
Os_Hal_UnhandledInterruptEntry(1, 46)
Os_Hal_UnhandledInterruptEntry(1, 47)
Os_Hal_UnhandledInterruptEntry(1, 48)
Os_Hal_UnhandledInterruptEntry(1, 49)
Os_Hal_UnhandledInterruptEntry(1, 50)
Os_Hal_UnhandledInterruptEntry(1, 51)
Os_Hal_UnhandledInterruptEntry(1, 52)
Os_Hal_UnhandledInterruptEntry(1, 53)
Os_Hal_UnhandledInterruptEntry(1, 54)
Os_Hal_UnhandledInterruptEntry(1, 55)
Os_Hal_UnhandledInterruptEntry(1, 56)
Os_Hal_UnhandledInterruptEntry(1, 57)
Os_Hal_UnhandledInterruptEntry(1, 58)
Os_Hal_UnhandledInterruptEntry(1, 59)
Os_Hal_UnhandledInterruptEntry(1, 60)
Os_Hal_UnhandledInterruptEntry(1, 61)
Os_Hal_UnhandledInterruptEntry(1, 62)
Os_Hal_UnhandledInterruptEntry(1, 63)
Os_Hal_UnhandledInterruptEntry(1, 64)
Os_Hal_UnhandledInterruptEntry(1, 65)
Os_Hal_UnhandledInterruptEntry(1, 66)
Os_Hal_UnhandledInterruptEntry(1, 67)
Os_Hal_UnhandledInterruptEntry(1, 68)
Os_Hal_UnhandledInterruptEntry(1, 69)
Os_Hal_UnhandledInterruptEntry(1, 70)
Os_Hal_UnhandledInterruptEntry(1, 71)
Os_Hal_UnhandledInterruptEntry(1, 72)
Os_Hal_UnhandledInterruptEntry(1, 73)
Os_Hal_UnhandledInterruptEntry(1, 74)
Os_Hal_UnhandledInterruptEntry(1, 75)
Os_Hal_UnhandledInterruptEntry(1, 76)
Os_Hal_UnhandledInterruptEntry(1, 77)
Os_Hal_UnhandledInterruptEntry(1, 78)
Os_Hal_UnhandledInterruptEntry(1, 79)
Os_Hal_UnhandledInterruptEntry(1, 80)
Os_Hal_UnhandledInterruptEntry(1, 81)
Os_Hal_UnhandledInterruptEntry(1, 82)
Os_Hal_UnhandledInterruptEntry(1, 83)
Os_Hal_UnhandledInterruptEntry(1, 84)
Os_Hal_UnhandledInterruptEntry(1, 85)
Os_Hal_UnhandledInterruptEntry(1, 86)
Os_Hal_UnhandledInterruptEntry(1, 87)
Os_Hal_UnhandledInterruptEntry(1, 88)
Os_Hal_UnhandledInterruptEntry(1, 89)
Os_Hal_UnhandledInterruptEntry(1, 90)
Os_Hal_UnhandledInterruptEntry(1, 91)
Os_Hal_UnhandledInterruptEntry(1, 92)
Os_Hal_UnhandledInterruptEntry(1, 93)
Os_Hal_UnhandledInterruptEntry(1, 94)
Os_Hal_UnhandledInterruptEntry(1, 95)
Os_Hal_UnhandledInterruptEntry(1, 96)
Os_Hal_UnhandledInterruptEntry(1, 97)
Os_Hal_UnhandledInterruptEntry(1, 98)
Os_Hal_UnhandledInterruptEntry(1, 99)
Os_Hal_UnhandledInterruptEntry(1, 100)
Os_Hal_UnhandledInterruptEntry(1, 101)
Os_Hal_UnhandledInterruptEntry(1, 102)
Os_Hal_UnhandledInterruptEntry(1, 103)
Os_Hal_UnhandledInterruptEntry(1, 104)
Os_Hal_UnhandledInterruptEntry(1, 105)
Os_Hal_UnhandledInterruptEntry(1, 106)
Os_Hal_UnhandledInterruptEntry(1, 107)
Os_Hal_UnhandledInterruptEntry(1, 108)
Os_Hal_UnhandledInterruptEntry(1, 109)
Os_Hal_UnhandledInterruptEntry(1, 110)
Os_Hal_UnhandledInterruptEntry(1, 111)
Os_Hal_UnhandledInterruptEntry(1, 112)
Os_Hal_UnhandledInterruptEntry(1, 113)
Os_Hal_UnhandledInterruptEntry(1, 114)
Os_Hal_UnhandledInterruptEntry(1, 115)
Os_Hal_UnhandledInterruptEntry(1, 116)
Os_Hal_UnhandledInterruptEntry(1, 117)
Os_Hal_UnhandledInterruptEntry(1, 118)
Os_Hal_UnhandledInterruptEntry(1, 119)
Os_Hal_UnhandledInterruptEntry(1, 120)
Os_Hal_UnhandledInterruptEntry(1, 121)
Os_Hal_UnhandledInterruptEntry(1, 122)
Os_Hal_UnhandledInterruptEntry(1, 123)
Os_Hal_UnhandledInterruptEntry(1, 124)
Os_Hal_UnhandledInterruptEntry(1, 125)
Os_Hal_UnhandledInterruptEntry(1, 126)
Os_Hal_UnhandledInterruptEntry(1, 127)
Os_Hal_UnhandledInterruptEntry(1, 128)
Os_Hal_UnhandledInterruptEntry(1, 129)
Os_Hal_UnhandledInterruptEntry(1, 130)
Os_Hal_UnhandledInterruptEntry(1, 131)
Os_Hal_UnhandledInterruptEntry(1, 132)
Os_Hal_UnhandledInterruptEntry(1, 133)
Os_Hal_UnhandledInterruptEntry(1, 134)
Os_Hal_UnhandledInterruptEntry(1, 135)
Os_Hal_UnhandledInterruptEntry(1, 136)
Os_Hal_UnhandledInterruptEntry(1, 137)
Os_Hal_UnhandledInterruptEntry(1, 138)
Os_Hal_UnhandledInterruptEntry(1, 139)
Os_Hal_UnhandledInterruptEntry(1, 140)
Os_Hal_UnhandledInterruptEntry(1, 141)
Os_Hal_UnhandledInterruptEntry(1, 142)
Os_Hal_UnhandledInterruptEntry(1, 143)
Os_Hal_UnhandledInterruptEntry(1, 144)
Os_Hal_UnhandledInterruptEntry(1, 145)
Os_Hal_UnhandledInterruptEntry(1, 146)
Os_Hal_UnhandledInterruptEntry(1, 147)
Os_Hal_UnhandledInterruptEntry(1, 148)
Os_Hal_UnhandledInterruptEntry(1, 149)
Os_Hal_UnhandledInterruptEntry(1, 150)
Os_Hal_UnhandledInterruptEntry(1, 151)
Os_Hal_UnhandledInterruptEntry(1, 152)
Os_Hal_UnhandledInterruptEntry(1, 153)
Os_Hal_UnhandledInterruptEntry(1, 154)
Os_Hal_UnhandledInterruptEntry(1, 155)
Os_Hal_UnhandledInterruptEntry(1, 156)
Os_Hal_UnhandledInterruptEntry(1, 157)
Os_Hal_UnhandledInterruptEntry(1, 158)
Os_Hal_UnhandledInterruptEntry(1, 159)
Os_Hal_UnhandledInterruptEntry(1, 160)
Os_Hal_UnhandledInterruptEntry(1, 161)
Os_Hal_UnhandledInterruptEntry(1, 162)
Os_Hal_UnhandledInterruptEntry(1, 163)
Os_Hal_UnhandledInterruptEntry(1, 164)
Os_Hal_UnhandledInterruptEntry(1, 165)
Os_Hal_UnhandledInterruptEntry(1, 166)
Os_Hal_UnhandledInterruptEntry(1, 167)
Os_Hal_UnhandledInterruptEntry(1, 168)
Os_Hal_UnhandledInterruptEntry(1, 169)
Os_Hal_UnhandledInterruptEntry(1, 170)
Os_Hal_UnhandledInterruptEntry(1, 171)
Os_Hal_UnhandledInterruptEntry(1, 172)
Os_Hal_UnhandledInterruptEntry(1, 173)
Os_Hal_UnhandledInterruptEntry(1, 174)
Os_Hal_UnhandledInterruptEntry(1, 175)
Os_Hal_UnhandledInterruptEntry(1, 176)
Os_Hal_UnhandledInterruptEntry(1, 177)
Os_Hal_UnhandledInterruptEntry(1, 178)
Os_Hal_UnhandledInterruptEntry(1, 179)
Os_Hal_UnhandledInterruptEntry(1, 180)
Os_Hal_UnhandledInterruptEntry(1, 181)
Os_Hal_UnhandledInterruptEntry(1, 182)
Os_Hal_UnhandledInterruptEntry(1, 183)
Os_Hal_UnhandledInterruptEntry(1, 184)
Os_Hal_UnhandledInterruptEntry(1, 185)
Os_Hal_UnhandledInterruptEntry(1, 186)
Os_Hal_UnhandledInterruptEntry(1, 187)
Os_Hal_UnhandledInterruptEntry(1, 188)
Os_Hal_UnhandledInterruptEntry(1, 189)
Os_Hal_UnhandledInterruptEntry(1, 190)
Os_Hal_UnhandledInterruptEntry(1, 191)
Os_Hal_UnhandledInterruptEntry(1, 192)
Os_Hal_UnhandledInterruptEntry(1, 193)
Os_Hal_UnhandledInterruptEntry(1, 194)
Os_Hal_UnhandledInterruptEntry(1, 195)
Os_Hal_UnhandledInterruptEntry(1, 196)
Os_Hal_UnhandledInterruptEntry(1, 197)
Os_Hal_UnhandledInterruptEntry(1, 198)
Os_Hal_UnhandledInterruptEntry(1, 199)
Os_Hal_UnhandledInterruptEntry(1, 200)
Os_Hal_UnhandledInterruptEntry(1, 201)
Os_Hal_UnhandledInterruptEntry(1, 202)
Os_Hal_UnhandledInterruptEntry(1, 203)
Os_Hal_UnhandledInterruptEntry(1, 204)
Os_Hal_UnhandledInterruptEntry(1, 205)
Os_Hal_UnhandledInterruptEntry(1, 206)
Os_Hal_UnhandledInterruptEntry(1, 207)
Os_Hal_UnhandledInterruptEntry(1, 208)
Os_Hal_UnhandledInterruptEntry(1, 209)
Os_Hal_UnhandledInterruptEntry(1, 210)
Os_Hal_UnhandledInterruptEntry(1, 211)
Os_Hal_UnhandledInterruptEntry(1, 212)
Os_Hal_UnhandledInterruptEntry(1, 213)
Os_Hal_UnhandledInterruptEntry(1, 214)
Os_Hal_UnhandledInterruptEntry(1, 215)
Os_Hal_UnhandledInterruptEntry(1, 216)
Os_Hal_UnhandledInterruptEntry(1, 217)
Os_Hal_UnhandledInterruptEntry(1, 218)
Os_Hal_UnhandledInterruptEntry(1, 219)
Os_Hal_UnhandledInterruptEntry(1, 220)
Os_Hal_UnhandledInterruptEntry(1, 221)
Os_Hal_UnhandledInterruptEntry(1, 222)
Os_Hal_UnhandledInterruptEntry(1, 223)
Os_Hal_UnhandledInterruptEntry(1, 224)
Os_Hal_UnhandledInterruptEntry(1, 225)
Os_Hal_UnhandledInterruptEntry(1, 226)
Os_Hal_UnhandledInterruptEntry(1, 227)
Os_Hal_UnhandledInterruptEntry(1, 228)
Os_Hal_UnhandledInterruptEntry(1, 229)
Os_Hal_UnhandledInterruptEntry(1, 230)
Os_Hal_UnhandledInterruptEntry(1, 231)
Os_Hal_UnhandledInterruptEntry(1, 232)
Os_Hal_UnhandledInterruptEntry(1, 233)
Os_Hal_UnhandledInterruptEntry(1, 234)
Os_Hal_UnhandledInterruptEntry(1, 235)
Os_Hal_UnhandledInterruptEntry(1, 236)
Os_Hal_UnhandledInterruptEntry(1, 237)
Os_Hal_UnhandledInterruptEntry(1, 238)
Os_Hal_UnhandledInterruptEntry(1, 239)
Os_Hal_UnhandledInterruptEntry(1, 240)
Os_Hal_UnhandledInterruptEntry(1, 241)
Os_Hal_UnhandledInterruptEntry(1, 242)
Os_Hal_UnhandledInterruptEntry(1, 243)
Os_Hal_UnhandledInterruptEntry(1, 244)
Os_Hal_UnhandledInterruptEntry(1, 245)
Os_Hal_UnhandledInterruptEntry(1, 246)
Os_Hal_UnhandledInterruptEntry(1, 247)
Os_Hal_UnhandledInterruptEntry(1, 248)
Os_Hal_UnhandledInterruptEntry(1, 249)
Os_Hal_UnhandledInterruptEntry(1, 250)
Os_Hal_UnhandledInterruptEntry(1, 251)
Os_Hal_UnhandledInterruptEntry(1, 252)
Os_Hal_UnhandledInterruptEntry(1, 253)
Os_Hal_UnhandledInterruptEntry(1, 254)
Os_Hal_UnhandledInterruptEntry(1, 255)

#define OS_STOP_SEC_INTVEC_CORE1_CODE
#include "Os_MemMap_OsSections.h" /* PRQA S 5087 */ /* MD_MSR_MemMap */


/**********************************************************************************************************************
 *  EXCEPTION VECTOR TABLE CORE 2
 *********************************************************************************************************************/

#define OS_START_SEC_EXCVEC_CORE2_CODE
#include "Os_MemMap_OsSections.h" /* PRQA S 5087 */ /* MD_MSR_MemMap */

Os_Hal_UnhandledTrapEntry(2, 0)
Os_Hal_UnhandledTrapEntry(2, 1)
Os_Hal_UnhandledTrapEntry(2, 2)
Os_Hal_UnhandledTrapEntry(2, 3)
Os_Hal_UnhandledTrapEntry(2, 4)
Os_Hal_UnhandledTrapEntry(2, 5)
Os_Hal_UnhandledTrapEntry(2, 6)
Os_Hal_UnhandledTrapEntry(2, 7)

#define OS_STOP_SEC_EXCVEC_CORE2_CODE
#include "Os_MemMap_OsSections.h" /* PRQA S 5087 */ /* MD_MSR_MemMap */


/**********************************************************************************************************************
 *  INTERRUPT VECTOR TABLE CORE 2
 *********************************************************************************************************************/

#define OS_START_SEC_INTVEC_CORE2_CODE
#include "Os_MemMap_OsSections.h" /* PRQA S 5087 */ /* MD_MSR_MemMap */

Os_Hal_UnhandledInterruptEntry(2, 0)
Os_Hal_UnhandledInterruptEntry(2, 1)
Os_Hal_UnhandledInterruptEntry(2, 2)
Os_Hal_UnhandledInterruptEntry(2, 3)
Os_Hal_UnhandledInterruptEntry(2, 4)
Os_Hal_UnhandledInterruptEntry(2, 5)
Os_Hal_UnhandledInterruptEntry(2, 6)
Os_Hal_UnhandledInterruptEntry(2, 7)
Os_Hal_UnhandledInterruptEntry(2, 8)
Os_Hal_UnhandledInterruptEntry(2, 9)
Os_Hal_UnhandledInterruptEntry(2, 10)
Os_Hal_UnhandledInterruptEntry(2, 11)
Os_Hal_UnhandledInterruptEntry(2, 12)
Os_Hal_UnhandledInterruptEntry(2, 13)
Os_Hal_UnhandledInterruptEntry(2, 14)
Os_Hal_UnhandledInterruptEntry(2, 15)
Os_Hal_UnhandledInterruptEntry(2, 16)
Os_Hal_UnhandledInterruptEntry(2, 17)
Os_Hal_Cat2InterruptEntry(2, 18, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_XSignalIsr_OsCore2)
Os_Hal_UnhandledInterruptEntry(2, 19)
Os_Hal_Cat2InterruptEntry(2, 20, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_CounterIsr_SystemTimer2)
Os_Hal_UnhandledInterruptEntry(2, 21)
Os_Hal_UnhandledInterruptEntry(2, 22)
Os_Hal_UnhandledInterruptEntry(2, 23)
Os_Hal_UnhandledInterruptEntry(2, 24)
Os_Hal_UnhandledInterruptEntry(2, 25)
Os_Hal_UnhandledInterruptEntry(2, 26)
Os_Hal_UnhandledInterruptEntry(2, 27)
Os_Hal_UnhandledInterruptEntry(2, 28)
Os_Hal_UnhandledInterruptEntry(2, 29)
Os_Hal_UnhandledInterruptEntry(2, 30)
Os_Hal_UnhandledInterruptEntry(2, 31)
Os_Hal_UnhandledInterruptEntry(2, 32)
Os_Hal_UnhandledInterruptEntry(2, 33)
Os_Hal_UnhandledInterruptEntry(2, 34)
Os_Hal_UnhandledInterruptEntry(2, 35)
Os_Hal_UnhandledInterruptEntry(2, 36)
Os_Hal_UnhandledInterruptEntry(2, 37)
Os_Hal_UnhandledInterruptEntry(2, 38)
Os_Hal_UnhandledInterruptEntry(2, 39)
Os_Hal_UnhandledInterruptEntry(2, 40)
Os_Hal_UnhandledInterruptEntry(2, 41)
Os_Hal_UnhandledInterruptEntry(2, 42)
Os_Hal_UnhandledInterruptEntry(2, 43)
Os_Hal_UnhandledInterruptEntry(2, 44)
Os_Hal_UnhandledInterruptEntry(2, 45)
Os_Hal_UnhandledInterruptEntry(2, 46)
Os_Hal_UnhandledInterruptEntry(2, 47)
Os_Hal_UnhandledInterruptEntry(2, 48)
Os_Hal_UnhandledInterruptEntry(2, 49)
Os_Hal_UnhandledInterruptEntry(2, 50)
Os_Hal_UnhandledInterruptEntry(2, 51)
Os_Hal_UnhandledInterruptEntry(2, 52)
Os_Hal_UnhandledInterruptEntry(2, 53)
Os_Hal_UnhandledInterruptEntry(2, 54)
Os_Hal_UnhandledInterruptEntry(2, 55)
Os_Hal_UnhandledInterruptEntry(2, 56)
Os_Hal_UnhandledInterruptEntry(2, 57)
Os_Hal_UnhandledInterruptEntry(2, 58)
Os_Hal_UnhandledInterruptEntry(2, 59)
Os_Hal_UnhandledInterruptEntry(2, 60)
Os_Hal_UnhandledInterruptEntry(2, 61)
Os_Hal_UnhandledInterruptEntry(2, 62)
Os_Hal_UnhandledInterruptEntry(2, 63)
Os_Hal_UnhandledInterruptEntry(2, 64)
Os_Hal_UnhandledInterruptEntry(2, 65)
Os_Hal_Cat2InterruptEntry(2, 66, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_CanIsr_1)
Os_Hal_UnhandledInterruptEntry(2, 67)
Os_Hal_UnhandledInterruptEntry(2, 68)
Os_Hal_UnhandledInterruptEntry(2, 69)
Os_Hal_UnhandledInterruptEntry(2, 70)
Os_Hal_UnhandledInterruptEntry(2, 71)
Os_Hal_UnhandledInterruptEntry(2, 72)
Os_Hal_UnhandledInterruptEntry(2, 73)
Os_Hal_UnhandledInterruptEntry(2, 74)
Os_Hal_UnhandledInterruptEntry(2, 75)
Os_Hal_UnhandledInterruptEntry(2, 76)
Os_Hal_UnhandledInterruptEntry(2, 77)
Os_Hal_UnhandledInterruptEntry(2, 78)
Os_Hal_UnhandledInterruptEntry(2, 79)
Os_Hal_UnhandledInterruptEntry(2, 80)
Os_Hal_UnhandledInterruptEntry(2, 81)
Os_Hal_UnhandledInterruptEntry(2, 82)
Os_Hal_UnhandledInterruptEntry(2, 83)
Os_Hal_UnhandledInterruptEntry(2, 84)
Os_Hal_UnhandledInterruptEntry(2, 85)
Os_Hal_UnhandledInterruptEntry(2, 86)
Os_Hal_UnhandledInterruptEntry(2, 87)
Os_Hal_UnhandledInterruptEntry(2, 88)
Os_Hal_UnhandledInterruptEntry(2, 89)
Os_Hal_UnhandledInterruptEntry(2, 90)
Os_Hal_UnhandledInterruptEntry(2, 91)
Os_Hal_UnhandledInterruptEntry(2, 92)
Os_Hal_UnhandledInterruptEntry(2, 93)
Os_Hal_UnhandledInterruptEntry(2, 94)
Os_Hal_UnhandledInterruptEntry(2, 95)
Os_Hal_UnhandledInterruptEntry(2, 96)
Os_Hal_UnhandledInterruptEntry(2, 97)
Os_Hal_UnhandledInterruptEntry(2, 98)
Os_Hal_UnhandledInterruptEntry(2, 99)
Os_Hal_UnhandledInterruptEntry(2, 100)
Os_Hal_UnhandledInterruptEntry(2, 101)
Os_Hal_UnhandledInterruptEntry(2, 102)
Os_Hal_UnhandledInterruptEntry(2, 103)
Os_Hal_UnhandledInterruptEntry(2, 104)
Os_Hal_UnhandledInterruptEntry(2, 105)
Os_Hal_UnhandledInterruptEntry(2, 106)
Os_Hal_UnhandledInterruptEntry(2, 107)
Os_Hal_UnhandledInterruptEntry(2, 108)
Os_Hal_UnhandledInterruptEntry(2, 109)
Os_Hal_UnhandledInterruptEntry(2, 110)
Os_Hal_UnhandledInterruptEntry(2, 111)
Os_Hal_UnhandledInterruptEntry(2, 112)
Os_Hal_UnhandledInterruptEntry(2, 113)
Os_Hal_UnhandledInterruptEntry(2, 114)
Os_Hal_UnhandledInterruptEntry(2, 115)
Os_Hal_UnhandledInterruptEntry(2, 116)
Os_Hal_UnhandledInterruptEntry(2, 117)
Os_Hal_UnhandledInterruptEntry(2, 118)
Os_Hal_UnhandledInterruptEntry(2, 119)
Os_Hal_UnhandledInterruptEntry(2, 120)
Os_Hal_UnhandledInterruptEntry(2, 121)
Os_Hal_UnhandledInterruptEntry(2, 122)
Os_Hal_UnhandledInterruptEntry(2, 123)
Os_Hal_UnhandledInterruptEntry(2, 124)
Os_Hal_UnhandledInterruptEntry(2, 125)
Os_Hal_UnhandledInterruptEntry(2, 126)
Os_Hal_UnhandledInterruptEntry(2, 127)
Os_Hal_UnhandledInterruptEntry(2, 128)
Os_Hal_UnhandledInterruptEntry(2, 129)
Os_Hal_UnhandledInterruptEntry(2, 130)
Os_Hal_UnhandledInterruptEntry(2, 131)
Os_Hal_UnhandledInterruptEntry(2, 132)
Os_Hal_UnhandledInterruptEntry(2, 133)
Os_Hal_UnhandledInterruptEntry(2, 134)
Os_Hal_UnhandledInterruptEntry(2, 135)
Os_Hal_UnhandledInterruptEntry(2, 136)
Os_Hal_UnhandledInterruptEntry(2, 137)
Os_Hal_UnhandledInterruptEntry(2, 138)
Os_Hal_UnhandledInterruptEntry(2, 139)
Os_Hal_UnhandledInterruptEntry(2, 140)
Os_Hal_UnhandledInterruptEntry(2, 141)
Os_Hal_UnhandledInterruptEntry(2, 142)
Os_Hal_UnhandledInterruptEntry(2, 143)
Os_Hal_UnhandledInterruptEntry(2, 144)
Os_Hal_UnhandledInterruptEntry(2, 145)
Os_Hal_UnhandledInterruptEntry(2, 146)
Os_Hal_UnhandledInterruptEntry(2, 147)
Os_Hal_UnhandledInterruptEntry(2, 148)
Os_Hal_UnhandledInterruptEntry(2, 149)
Os_Hal_UnhandledInterruptEntry(2, 150)
Os_Hal_UnhandledInterruptEntry(2, 151)
Os_Hal_UnhandledInterruptEntry(2, 152)
Os_Hal_UnhandledInterruptEntry(2, 153)
Os_Hal_UnhandledInterruptEntry(2, 154)
Os_Hal_UnhandledInterruptEntry(2, 155)
Os_Hal_UnhandledInterruptEntry(2, 156)
Os_Hal_UnhandledInterruptEntry(2, 157)
Os_Hal_UnhandledInterruptEntry(2, 158)
Os_Hal_UnhandledInterruptEntry(2, 159)
Os_Hal_UnhandledInterruptEntry(2, 160)
Os_Hal_UnhandledInterruptEntry(2, 161)
Os_Hal_UnhandledInterruptEntry(2, 162)
Os_Hal_UnhandledInterruptEntry(2, 163)
Os_Hal_UnhandledInterruptEntry(2, 164)
Os_Hal_UnhandledInterruptEntry(2, 165)
Os_Hal_UnhandledInterruptEntry(2, 166)
Os_Hal_UnhandledInterruptEntry(2, 167)
Os_Hal_UnhandledInterruptEntry(2, 168)
Os_Hal_UnhandledInterruptEntry(2, 169)
Os_Hal_UnhandledInterruptEntry(2, 170)
Os_Hal_UnhandledInterruptEntry(2, 171)
Os_Hal_UnhandledInterruptEntry(2, 172)
Os_Hal_UnhandledInterruptEntry(2, 173)
Os_Hal_UnhandledInterruptEntry(2, 174)
Os_Hal_UnhandledInterruptEntry(2, 175)
Os_Hal_UnhandledInterruptEntry(2, 176)
Os_Hal_UnhandledInterruptEntry(2, 177)
Os_Hal_UnhandledInterruptEntry(2, 178)
Os_Hal_UnhandledInterruptEntry(2, 179)
Os_Hal_UnhandledInterruptEntry(2, 180)
Os_Hal_UnhandledInterruptEntry(2, 181)
Os_Hal_UnhandledInterruptEntry(2, 182)
Os_Hal_UnhandledInterruptEntry(2, 183)
Os_Hal_UnhandledInterruptEntry(2, 184)
Os_Hal_UnhandledInterruptEntry(2, 185)
Os_Hal_UnhandledInterruptEntry(2, 186)
Os_Hal_UnhandledInterruptEntry(2, 187)
Os_Hal_UnhandledInterruptEntry(2, 188)
Os_Hal_UnhandledInterruptEntry(2, 189)
Os_Hal_UnhandledInterruptEntry(2, 190)
Os_Hal_UnhandledInterruptEntry(2, 191)
Os_Hal_UnhandledInterruptEntry(2, 192)
Os_Hal_UnhandledInterruptEntry(2, 193)
Os_Hal_UnhandledInterruptEntry(2, 194)
Os_Hal_UnhandledInterruptEntry(2, 195)
Os_Hal_UnhandledInterruptEntry(2, 196)
Os_Hal_UnhandledInterruptEntry(2, 197)
Os_Hal_UnhandledInterruptEntry(2, 198)
Os_Hal_UnhandledInterruptEntry(2, 199)
Os_Hal_UnhandledInterruptEntry(2, 200)
Os_Hal_UnhandledInterruptEntry(2, 201)
Os_Hal_UnhandledInterruptEntry(2, 202)
Os_Hal_UnhandledInterruptEntry(2, 203)
Os_Hal_UnhandledInterruptEntry(2, 204)
Os_Hal_UnhandledInterruptEntry(2, 205)
Os_Hal_UnhandledInterruptEntry(2, 206)
Os_Hal_UnhandledInterruptEntry(2, 207)
Os_Hal_UnhandledInterruptEntry(2, 208)
Os_Hal_UnhandledInterruptEntry(2, 209)
Os_Hal_UnhandledInterruptEntry(2, 210)
Os_Hal_UnhandledInterruptEntry(2, 211)
Os_Hal_UnhandledInterruptEntry(2, 212)
Os_Hal_UnhandledInterruptEntry(2, 213)
Os_Hal_UnhandledInterruptEntry(2, 214)
Os_Hal_UnhandledInterruptEntry(2, 215)
Os_Hal_UnhandledInterruptEntry(2, 216)
Os_Hal_UnhandledInterruptEntry(2, 217)
Os_Hal_UnhandledInterruptEntry(2, 218)
Os_Hal_UnhandledInterruptEntry(2, 219)
Os_Hal_UnhandledInterruptEntry(2, 220)
Os_Hal_UnhandledInterruptEntry(2, 221)
Os_Hal_UnhandledInterruptEntry(2, 222)
Os_Hal_UnhandledInterruptEntry(2, 223)
Os_Hal_UnhandledInterruptEntry(2, 224)
Os_Hal_UnhandledInterruptEntry(2, 225)
Os_Hal_UnhandledInterruptEntry(2, 226)
Os_Hal_UnhandledInterruptEntry(2, 227)
Os_Hal_UnhandledInterruptEntry(2, 228)
Os_Hal_UnhandledInterruptEntry(2, 229)
Os_Hal_UnhandledInterruptEntry(2, 230)
Os_Hal_UnhandledInterruptEntry(2, 231)
Os_Hal_UnhandledInterruptEntry(2, 232)
Os_Hal_UnhandledInterruptEntry(2, 233)
Os_Hal_UnhandledInterruptEntry(2, 234)
Os_Hal_UnhandledInterruptEntry(2, 235)
Os_Hal_UnhandledInterruptEntry(2, 236)
Os_Hal_UnhandledInterruptEntry(2, 237)
Os_Hal_UnhandledInterruptEntry(2, 238)
Os_Hal_UnhandledInterruptEntry(2, 239)
Os_Hal_UnhandledInterruptEntry(2, 240)
Os_Hal_UnhandledInterruptEntry(2, 241)
Os_Hal_UnhandledInterruptEntry(2, 242)
Os_Hal_UnhandledInterruptEntry(2, 243)
Os_Hal_UnhandledInterruptEntry(2, 244)
Os_Hal_UnhandledInterruptEntry(2, 245)
Os_Hal_UnhandledInterruptEntry(2, 246)
Os_Hal_UnhandledInterruptEntry(2, 247)
Os_Hal_UnhandledInterruptEntry(2, 248)
Os_Hal_UnhandledInterruptEntry(2, 249)
Os_Hal_UnhandledInterruptEntry(2, 250)
Os_Hal_UnhandledInterruptEntry(2, 251)
Os_Hal_UnhandledInterruptEntry(2, 252)
Os_Hal_UnhandledInterruptEntry(2, 253)
Os_Hal_UnhandledInterruptEntry(2, 254)
Os_Hal_UnhandledInterruptEntry(2, 255)

#define OS_STOP_SEC_INTVEC_CORE2_CODE
#include "Os_MemMap_OsSections.h" /* PRQA S 5087 */ /* MD_MSR_MemMap */


/**********************************************************************************************************************
 *  EXCEPTION VECTOR TABLE CORE 3
 *********************************************************************************************************************/

#define OS_START_SEC_EXCVEC_CORE3_CODE
#include "Os_MemMap_OsSections.h" /* PRQA S 5087 */ /* MD_MSR_MemMap */

Os_Hal_UnhandledTrapEntry(3, 0)
Os_Hal_UnhandledTrapEntry(3, 1)
Os_Hal_UnhandledTrapEntry(3, 2)
Os_Hal_UnhandledTrapEntry(3, 3)
Os_Hal_UnhandledTrapEntry(3, 4)
Os_Hal_UnhandledTrapEntry(3, 5)
Os_Hal_UnhandledTrapEntry(3, 6)
Os_Hal_UnhandledTrapEntry(3, 7)

#define OS_STOP_SEC_EXCVEC_CORE3_CODE
#include "Os_MemMap_OsSections.h" /* PRQA S 5087 */ /* MD_MSR_MemMap */


/**********************************************************************************************************************
 *  INTERRUPT VECTOR TABLE CORE 3
 *********************************************************************************************************************/

#define OS_START_SEC_INTVEC_CORE3_CODE
#include "Os_MemMap_OsSections.h" /* PRQA S 5087 */ /* MD_MSR_MemMap */

Os_Hal_UnhandledInterruptEntry(3, 0)
Os_Hal_UnhandledInterruptEntry(3, 1)
Os_Hal_UnhandledInterruptEntry(3, 2)
Os_Hal_UnhandledInterruptEntry(3, 3)
Os_Hal_UnhandledInterruptEntry(3, 4)
Os_Hal_UnhandledInterruptEntry(3, 5)
Os_Hal_UnhandledInterruptEntry(3, 6)
Os_Hal_UnhandledInterruptEntry(3, 7)
Os_Hal_UnhandledInterruptEntry(3, 8)
Os_Hal_UnhandledInterruptEntry(3, 9)
Os_Hal_UnhandledInterruptEntry(3, 10)
Os_Hal_UnhandledInterruptEntry(3, 11)
Os_Hal_UnhandledInterruptEntry(3, 12)
Os_Hal_UnhandledInterruptEntry(3, 13)
Os_Hal_UnhandledInterruptEntry(3, 14)
Os_Hal_UnhandledInterruptEntry(3, 15)
Os_Hal_UnhandledInterruptEntry(3, 16)
Os_Hal_UnhandledInterruptEntry(3, 17)
Os_Hal_Cat2InterruptEntry(3, 18, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_XSignalIsr_OsCore3)
Os_Hal_UnhandledInterruptEntry(3, 19)
Os_Hal_Cat2InterruptEntry(3, 20, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_CounterIsr_SystemTimer3)
Os_Hal_UnhandledInterruptEntry(3, 21)
Os_Hal_UnhandledInterruptEntry(3, 22)
Os_Hal_UnhandledInterruptEntry(3, 23)
Os_Hal_UnhandledInterruptEntry(3, 24)
Os_Hal_UnhandledInterruptEntry(3, 25)
Os_Hal_UnhandledInterruptEntry(3, 26)
Os_Hal_UnhandledInterruptEntry(3, 27)
Os_Hal_UnhandledInterruptEntry(3, 28)
Os_Hal_UnhandledInterruptEntry(3, 29)
Os_Hal_UnhandledInterruptEntry(3, 30)
Os_Hal_UnhandledInterruptEntry(3, 31)
Os_Hal_UnhandledInterruptEntry(3, 32)
Os_Hal_UnhandledInterruptEntry(3, 33)
Os_Hal_UnhandledInterruptEntry(3, 34)
Os_Hal_UnhandledInterruptEntry(3, 35)
Os_Hal_UnhandledInterruptEntry(3, 36)
Os_Hal_UnhandledInterruptEntry(3, 37)
Os_Hal_UnhandledInterruptEntry(3, 38)
Os_Hal_UnhandledInterruptEntry(3, 39)
Os_Hal_UnhandledInterruptEntry(3, 40)
Os_Hal_UnhandledInterruptEntry(3, 41)
Os_Hal_UnhandledInterruptEntry(3, 42)
Os_Hal_UnhandledInterruptEntry(3, 43)
Os_Hal_UnhandledInterruptEntry(3, 44)
Os_Hal_UnhandledInterruptEntry(3, 45)
Os_Hal_UnhandledInterruptEntry(3, 46)
Os_Hal_UnhandledInterruptEntry(3, 47)
Os_Hal_UnhandledInterruptEntry(3, 48)
Os_Hal_UnhandledInterruptEntry(3, 49)
Os_Hal_UnhandledInterruptEntry(3, 50)
Os_Hal_UnhandledInterruptEntry(3, 51)
Os_Hal_UnhandledInterruptEntry(3, 52)
Os_Hal_UnhandledInterruptEntry(3, 53)
Os_Hal_UnhandledInterruptEntry(3, 54)
Os_Hal_UnhandledInterruptEntry(3, 55)
Os_Hal_UnhandledInterruptEntry(3, 56)
Os_Hal_UnhandledInterruptEntry(3, 57)
Os_Hal_UnhandledInterruptEntry(3, 58)
Os_Hal_UnhandledInterruptEntry(3, 59)
Os_Hal_UnhandledInterruptEntry(3, 60)
Os_Hal_UnhandledInterruptEntry(3, 61)
Os_Hal_UnhandledInterruptEntry(3, 62)
Os_Hal_UnhandledInterruptEntry(3, 63)
Os_Hal_UnhandledInterruptEntry(3, 64)
Os_Hal_UnhandledInterruptEntry(3, 65)
Os_Hal_UnhandledInterruptEntry(3, 66)
Os_Hal_Cat2InterruptEntry(3, 67, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_CanIsr_2)
Os_Hal_UnhandledInterruptEntry(3, 68)
Os_Hal_UnhandledInterruptEntry(3, 69)
Os_Hal_UnhandledInterruptEntry(3, 70)
Os_Hal_UnhandledInterruptEntry(3, 71)
Os_Hal_UnhandledInterruptEntry(3, 72)
Os_Hal_UnhandledInterruptEntry(3, 73)
Os_Hal_UnhandledInterruptEntry(3, 74)
Os_Hal_UnhandledInterruptEntry(3, 75)
Os_Hal_UnhandledInterruptEntry(3, 76)
Os_Hal_UnhandledInterruptEntry(3, 77)
Os_Hal_UnhandledInterruptEntry(3, 78)
Os_Hal_UnhandledInterruptEntry(3, 79)
Os_Hal_UnhandledInterruptEntry(3, 80)
Os_Hal_UnhandledInterruptEntry(3, 81)
Os_Hal_UnhandledInterruptEntry(3, 82)
Os_Hal_UnhandledInterruptEntry(3, 83)
Os_Hal_UnhandledInterruptEntry(3, 84)
Os_Hal_UnhandledInterruptEntry(3, 85)
Os_Hal_UnhandledInterruptEntry(3, 86)
Os_Hal_UnhandledInterruptEntry(3, 87)
Os_Hal_UnhandledInterruptEntry(3, 88)
Os_Hal_UnhandledInterruptEntry(3, 89)
Os_Hal_UnhandledInterruptEntry(3, 90)
Os_Hal_UnhandledInterruptEntry(3, 91)
Os_Hal_UnhandledInterruptEntry(3, 92)
Os_Hal_UnhandledInterruptEntry(3, 93)
Os_Hal_UnhandledInterruptEntry(3, 94)
Os_Hal_UnhandledInterruptEntry(3, 95)
Os_Hal_UnhandledInterruptEntry(3, 96)
Os_Hal_UnhandledInterruptEntry(3, 97)
Os_Hal_UnhandledInterruptEntry(3, 98)
Os_Hal_UnhandledInterruptEntry(3, 99)
Os_Hal_UnhandledInterruptEntry(3, 100)
Os_Hal_UnhandledInterruptEntry(3, 101)
Os_Hal_UnhandledInterruptEntry(3, 102)
Os_Hal_UnhandledInterruptEntry(3, 103)
Os_Hal_UnhandledInterruptEntry(3, 104)
Os_Hal_UnhandledInterruptEntry(3, 105)
Os_Hal_UnhandledInterruptEntry(3, 106)
Os_Hal_UnhandledInterruptEntry(3, 107)
Os_Hal_UnhandledInterruptEntry(3, 108)
Os_Hal_UnhandledInterruptEntry(3, 109)
Os_Hal_UnhandledInterruptEntry(3, 110)
Os_Hal_UnhandledInterruptEntry(3, 111)
Os_Hal_UnhandledInterruptEntry(3, 112)
Os_Hal_UnhandledInterruptEntry(3, 113)
Os_Hal_UnhandledInterruptEntry(3, 114)
Os_Hal_UnhandledInterruptEntry(3, 115)
Os_Hal_UnhandledInterruptEntry(3, 116)
Os_Hal_UnhandledInterruptEntry(3, 117)
Os_Hal_UnhandledInterruptEntry(3, 118)
Os_Hal_UnhandledInterruptEntry(3, 119)
Os_Hal_UnhandledInterruptEntry(3, 120)
Os_Hal_UnhandledInterruptEntry(3, 121)
Os_Hal_UnhandledInterruptEntry(3, 122)
Os_Hal_UnhandledInterruptEntry(3, 123)
Os_Hal_UnhandledInterruptEntry(3, 124)
Os_Hal_UnhandledInterruptEntry(3, 125)
Os_Hal_UnhandledInterruptEntry(3, 126)
Os_Hal_UnhandledInterruptEntry(3, 127)
Os_Hal_UnhandledInterruptEntry(3, 128)
Os_Hal_UnhandledInterruptEntry(3, 129)
Os_Hal_UnhandledInterruptEntry(3, 130)
Os_Hal_UnhandledInterruptEntry(3, 131)
Os_Hal_UnhandledInterruptEntry(3, 132)
Os_Hal_UnhandledInterruptEntry(3, 133)
Os_Hal_UnhandledInterruptEntry(3, 134)
Os_Hal_UnhandledInterruptEntry(3, 135)
Os_Hal_UnhandledInterruptEntry(3, 136)
Os_Hal_UnhandledInterruptEntry(3, 137)
Os_Hal_UnhandledInterruptEntry(3, 138)
Os_Hal_UnhandledInterruptEntry(3, 139)
Os_Hal_UnhandledInterruptEntry(3, 140)
Os_Hal_UnhandledInterruptEntry(3, 141)
Os_Hal_UnhandledInterruptEntry(3, 142)
Os_Hal_UnhandledInterruptEntry(3, 143)
Os_Hal_UnhandledInterruptEntry(3, 144)
Os_Hal_UnhandledInterruptEntry(3, 145)
Os_Hal_UnhandledInterruptEntry(3, 146)
Os_Hal_UnhandledInterruptEntry(3, 147)
Os_Hal_UnhandledInterruptEntry(3, 148)
Os_Hal_UnhandledInterruptEntry(3, 149)
Os_Hal_UnhandledInterruptEntry(3, 150)
Os_Hal_UnhandledInterruptEntry(3, 151)
Os_Hal_UnhandledInterruptEntry(3, 152)
Os_Hal_UnhandledInterruptEntry(3, 153)
Os_Hal_UnhandledInterruptEntry(3, 154)
Os_Hal_UnhandledInterruptEntry(3, 155)
Os_Hal_UnhandledInterruptEntry(3, 156)
Os_Hal_UnhandledInterruptEntry(3, 157)
Os_Hal_UnhandledInterruptEntry(3, 158)
Os_Hal_UnhandledInterruptEntry(3, 159)
Os_Hal_UnhandledInterruptEntry(3, 160)
Os_Hal_UnhandledInterruptEntry(3, 161)
Os_Hal_UnhandledInterruptEntry(3, 162)
Os_Hal_UnhandledInterruptEntry(3, 163)
Os_Hal_UnhandledInterruptEntry(3, 164)
Os_Hal_UnhandledInterruptEntry(3, 165)
Os_Hal_UnhandledInterruptEntry(3, 166)
Os_Hal_UnhandledInterruptEntry(3, 167)
Os_Hal_UnhandledInterruptEntry(3, 168)
Os_Hal_UnhandledInterruptEntry(3, 169)
Os_Hal_UnhandledInterruptEntry(3, 170)
Os_Hal_UnhandledInterruptEntry(3, 171)
Os_Hal_UnhandledInterruptEntry(3, 172)
Os_Hal_UnhandledInterruptEntry(3, 173)
Os_Hal_UnhandledInterruptEntry(3, 174)
Os_Hal_UnhandledInterruptEntry(3, 175)
Os_Hal_UnhandledInterruptEntry(3, 176)
Os_Hal_UnhandledInterruptEntry(3, 177)
Os_Hal_UnhandledInterruptEntry(3, 178)
Os_Hal_UnhandledInterruptEntry(3, 179)
Os_Hal_UnhandledInterruptEntry(3, 180)
Os_Hal_UnhandledInterruptEntry(3, 181)
Os_Hal_UnhandledInterruptEntry(3, 182)
Os_Hal_UnhandledInterruptEntry(3, 183)
Os_Hal_UnhandledInterruptEntry(3, 184)
Os_Hal_UnhandledInterruptEntry(3, 185)
Os_Hal_UnhandledInterruptEntry(3, 186)
Os_Hal_UnhandledInterruptEntry(3, 187)
Os_Hal_UnhandledInterruptEntry(3, 188)
Os_Hal_UnhandledInterruptEntry(3, 189)
Os_Hal_UnhandledInterruptEntry(3, 190)
Os_Hal_UnhandledInterruptEntry(3, 191)
Os_Hal_UnhandledInterruptEntry(3, 192)
Os_Hal_UnhandledInterruptEntry(3, 193)
Os_Hal_UnhandledInterruptEntry(3, 194)
Os_Hal_UnhandledInterruptEntry(3, 195)
Os_Hal_UnhandledInterruptEntry(3, 196)
Os_Hal_UnhandledInterruptEntry(3, 197)
Os_Hal_UnhandledInterruptEntry(3, 198)
Os_Hal_UnhandledInterruptEntry(3, 199)
Os_Hal_UnhandledInterruptEntry(3, 200)
Os_Hal_UnhandledInterruptEntry(3, 201)
Os_Hal_UnhandledInterruptEntry(3, 202)
Os_Hal_UnhandledInterruptEntry(3, 203)
Os_Hal_UnhandledInterruptEntry(3, 204)
Os_Hal_UnhandledInterruptEntry(3, 205)
Os_Hal_UnhandledInterruptEntry(3, 206)
Os_Hal_UnhandledInterruptEntry(3, 207)
Os_Hal_UnhandledInterruptEntry(3, 208)
Os_Hal_UnhandledInterruptEntry(3, 209)
Os_Hal_UnhandledInterruptEntry(3, 210)
Os_Hal_UnhandledInterruptEntry(3, 211)
Os_Hal_UnhandledInterruptEntry(3, 212)
Os_Hal_UnhandledInterruptEntry(3, 213)
Os_Hal_UnhandledInterruptEntry(3, 214)
Os_Hal_UnhandledInterruptEntry(3, 215)
Os_Hal_UnhandledInterruptEntry(3, 216)
Os_Hal_UnhandledInterruptEntry(3, 217)
Os_Hal_UnhandledInterruptEntry(3, 218)
Os_Hal_UnhandledInterruptEntry(3, 219)
Os_Hal_UnhandledInterruptEntry(3, 220)
Os_Hal_UnhandledInterruptEntry(3, 221)
Os_Hal_UnhandledInterruptEntry(3, 222)
Os_Hal_UnhandledInterruptEntry(3, 223)
Os_Hal_UnhandledInterruptEntry(3, 224)
Os_Hal_UnhandledInterruptEntry(3, 225)
Os_Hal_UnhandledInterruptEntry(3, 226)
Os_Hal_UnhandledInterruptEntry(3, 227)
Os_Hal_UnhandledInterruptEntry(3, 228)
Os_Hal_UnhandledInterruptEntry(3, 229)
Os_Hal_UnhandledInterruptEntry(3, 230)
Os_Hal_UnhandledInterruptEntry(3, 231)
Os_Hal_UnhandledInterruptEntry(3, 232)
Os_Hal_UnhandledInterruptEntry(3, 233)
Os_Hal_UnhandledInterruptEntry(3, 234)
Os_Hal_UnhandledInterruptEntry(3, 235)
Os_Hal_UnhandledInterruptEntry(3, 236)
Os_Hal_UnhandledInterruptEntry(3, 237)
Os_Hal_UnhandledInterruptEntry(3, 238)
Os_Hal_UnhandledInterruptEntry(3, 239)
Os_Hal_UnhandledInterruptEntry(3, 240)
Os_Hal_UnhandledInterruptEntry(3, 241)
Os_Hal_UnhandledInterruptEntry(3, 242)
Os_Hal_UnhandledInterruptEntry(3, 243)
Os_Hal_UnhandledInterruptEntry(3, 244)
Os_Hal_UnhandledInterruptEntry(3, 245)
Os_Hal_UnhandledInterruptEntry(3, 246)
Os_Hal_UnhandledInterruptEntry(3, 247)
Os_Hal_UnhandledInterruptEntry(3, 248)
Os_Hal_UnhandledInterruptEntry(3, 249)
Os_Hal_UnhandledInterruptEntry(3, 250)
Os_Hal_UnhandledInterruptEntry(3, 251)
Os_Hal_UnhandledInterruptEntry(3, 252)
Os_Hal_UnhandledInterruptEntry(3, 253)
Os_Hal_UnhandledInterruptEntry(3, 254)
Os_Hal_UnhandledInterruptEntry(3, 255)

#define OS_STOP_SEC_INTVEC_CORE3_CODE
#include "Os_MemMap_OsSections.h" /* PRQA S 5087 */ /* MD_MSR_MemMap */


/**********************************************************************************************************************
 *  EXCEPTION VECTOR TABLE CORE 4
 *********************************************************************************************************************/

#define OS_START_SEC_EXCVEC_CORE4_CODE
#include "Os_MemMap_OsSections.h" /* PRQA S 5087 */ /* MD_MSR_MemMap */

Os_Hal_UnhandledTrapEntry(4, 0)
Os_Hal_UnhandledTrapEntry(4, 1)
Os_Hal_UnhandledTrapEntry(4, 2)
Os_Hal_UnhandledTrapEntry(4, 3)
Os_Hal_UnhandledTrapEntry(4, 4)
Os_Hal_UnhandledTrapEntry(4, 5)
Os_Hal_UnhandledTrapEntry(4, 6)
Os_Hal_UnhandledTrapEntry(4, 7)

#define OS_STOP_SEC_EXCVEC_CORE4_CODE
#include "Os_MemMap_OsSections.h" /* PRQA S 5087 */ /* MD_MSR_MemMap */


/**********************************************************************************************************************
 *  INTERRUPT VECTOR TABLE CORE 4
 *********************************************************************************************************************/

#define OS_START_SEC_INTVEC_CORE4_CODE
#include "Os_MemMap_OsSections.h" /* PRQA S 5087 */ /* MD_MSR_MemMap */

Os_Hal_UnhandledInterruptEntry(4, 0)
Os_Hal_UnhandledInterruptEntry(4, 1)
Os_Hal_UnhandledInterruptEntry(4, 2)
Os_Hal_UnhandledInterruptEntry(4, 3)
Os_Hal_UnhandledInterruptEntry(4, 4)
Os_Hal_UnhandledInterruptEntry(4, 5)
Os_Hal_UnhandledInterruptEntry(4, 6)
Os_Hal_UnhandledInterruptEntry(4, 7)
Os_Hal_UnhandledInterruptEntry(4, 8)
Os_Hal_UnhandledInterruptEntry(4, 9)
Os_Hal_UnhandledInterruptEntry(4, 10)
Os_Hal_UnhandledInterruptEntry(4, 11)
Os_Hal_UnhandledInterruptEntry(4, 12)
Os_Hal_UnhandledInterruptEntry(4, 13)
Os_Hal_UnhandledInterruptEntry(4, 14)
Os_Hal_UnhandledInterruptEntry(4, 15)
Os_Hal_UnhandledInterruptEntry(4, 16)
Os_Hal_UnhandledInterruptEntry(4, 17)
Os_Hal_Cat2InterruptEntry(4, 18, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_XSignalIsr_OsCore4)
Os_Hal_UnhandledInterruptEntry(4, 19)
Os_Hal_Cat2InterruptEntry(4, 20, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_CounterIsr_SystemTimer4)
Os_Hal_UnhandledInterruptEntry(4, 21)
Os_Hal_UnhandledInterruptEntry(4, 22)
Os_Hal_UnhandledInterruptEntry(4, 23)
Os_Hal_UnhandledInterruptEntry(4, 24)
Os_Hal_UnhandledInterruptEntry(4, 25)
Os_Hal_UnhandledInterruptEntry(4, 26)
Os_Hal_UnhandledInterruptEntry(4, 27)
Os_Hal_UnhandledInterruptEntry(4, 28)
Os_Hal_UnhandledInterruptEntry(4, 29)
Os_Hal_UnhandledInterruptEntry(4, 30)
Os_Hal_UnhandledInterruptEntry(4, 31)
Os_Hal_UnhandledInterruptEntry(4, 32)
Os_Hal_UnhandledInterruptEntry(4, 33)
Os_Hal_UnhandledInterruptEntry(4, 34)
Os_Hal_UnhandledInterruptEntry(4, 35)
Os_Hal_UnhandledInterruptEntry(4, 36)
Os_Hal_UnhandledInterruptEntry(4, 37)
Os_Hal_UnhandledInterruptEntry(4, 38)
Os_Hal_UnhandledInterruptEntry(4, 39)
Os_Hal_UnhandledInterruptEntry(4, 40)
Os_Hal_UnhandledInterruptEntry(4, 41)
Os_Hal_UnhandledInterruptEntry(4, 42)
Os_Hal_UnhandledInterruptEntry(4, 43)
Os_Hal_UnhandledInterruptEntry(4, 44)
Os_Hal_UnhandledInterruptEntry(4, 45)
Os_Hal_UnhandledInterruptEntry(4, 46)
Os_Hal_UnhandledInterruptEntry(4, 47)
Os_Hal_UnhandledInterruptEntry(4, 48)
Os_Hal_UnhandledInterruptEntry(4, 49)
Os_Hal_UnhandledInterruptEntry(4, 50)
Os_Hal_UnhandledInterruptEntry(4, 51)
Os_Hal_UnhandledInterruptEntry(4, 52)
Os_Hal_UnhandledInterruptEntry(4, 53)
Os_Hal_UnhandledInterruptEntry(4, 54)
Os_Hal_UnhandledInterruptEntry(4, 55)
Os_Hal_UnhandledInterruptEntry(4, 56)
Os_Hal_UnhandledInterruptEntry(4, 57)
Os_Hal_UnhandledInterruptEntry(4, 58)
Os_Hal_UnhandledInterruptEntry(4, 59)
Os_Hal_UnhandledInterruptEntry(4, 60)
Os_Hal_UnhandledInterruptEntry(4, 61)
Os_Hal_UnhandledInterruptEntry(4, 62)
Os_Hal_UnhandledInterruptEntry(4, 63)
Os_Hal_UnhandledInterruptEntry(4, 64)
Os_Hal_UnhandledInterruptEntry(4, 65)
Os_Hal_UnhandledInterruptEntry(4, 66)
Os_Hal_UnhandledInterruptEntry(4, 67)
Os_Hal_Cat2InterruptEntry(4, 68, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_CanIsr_3)
Os_Hal_UnhandledInterruptEntry(4, 69)
Os_Hal_UnhandledInterruptEntry(4, 70)
Os_Hal_UnhandledInterruptEntry(4, 71)
Os_Hal_UnhandledInterruptEntry(4, 72)
Os_Hal_UnhandledInterruptEntry(4, 73)
Os_Hal_UnhandledInterruptEntry(4, 74)
Os_Hal_UnhandledInterruptEntry(4, 75)
Os_Hal_UnhandledInterruptEntry(4, 76)
Os_Hal_UnhandledInterruptEntry(4, 77)
Os_Hal_UnhandledInterruptEntry(4, 78)
Os_Hal_UnhandledInterruptEntry(4, 79)
Os_Hal_UnhandledInterruptEntry(4, 80)
Os_Hal_UnhandledInterruptEntry(4, 81)
Os_Hal_UnhandledInterruptEntry(4, 82)
Os_Hal_UnhandledInterruptEntry(4, 83)
Os_Hal_UnhandledInterruptEntry(4, 84)
Os_Hal_UnhandledInterruptEntry(4, 85)
Os_Hal_UnhandledInterruptEntry(4, 86)
Os_Hal_UnhandledInterruptEntry(4, 87)
Os_Hal_UnhandledInterruptEntry(4, 88)
Os_Hal_UnhandledInterruptEntry(4, 89)
Os_Hal_UnhandledInterruptEntry(4, 90)
Os_Hal_UnhandledInterruptEntry(4, 91)
Os_Hal_UnhandledInterruptEntry(4, 92)
Os_Hal_UnhandledInterruptEntry(4, 93)
Os_Hal_UnhandledInterruptEntry(4, 94)
Os_Hal_UnhandledInterruptEntry(4, 95)
Os_Hal_UnhandledInterruptEntry(4, 96)
Os_Hal_UnhandledInterruptEntry(4, 97)
Os_Hal_UnhandledInterruptEntry(4, 98)
Os_Hal_UnhandledInterruptEntry(4, 99)
Os_Hal_UnhandledInterruptEntry(4, 100)
Os_Hal_UnhandledInterruptEntry(4, 101)
Os_Hal_UnhandledInterruptEntry(4, 102)
Os_Hal_UnhandledInterruptEntry(4, 103)
Os_Hal_UnhandledInterruptEntry(4, 104)
Os_Hal_UnhandledInterruptEntry(4, 105)
Os_Hal_UnhandledInterruptEntry(4, 106)
Os_Hal_UnhandledInterruptEntry(4, 107)
Os_Hal_UnhandledInterruptEntry(4, 108)
Os_Hal_UnhandledInterruptEntry(4, 109)
Os_Hal_UnhandledInterruptEntry(4, 110)
Os_Hal_UnhandledInterruptEntry(4, 111)
Os_Hal_UnhandledInterruptEntry(4, 112)
Os_Hal_UnhandledInterruptEntry(4, 113)
Os_Hal_UnhandledInterruptEntry(4, 114)
Os_Hal_UnhandledInterruptEntry(4, 115)
Os_Hal_UnhandledInterruptEntry(4, 116)
Os_Hal_UnhandledInterruptEntry(4, 117)
Os_Hal_UnhandledInterruptEntry(4, 118)
Os_Hal_UnhandledInterruptEntry(4, 119)
Os_Hal_UnhandledInterruptEntry(4, 120)
Os_Hal_UnhandledInterruptEntry(4, 121)
Os_Hal_UnhandledInterruptEntry(4, 122)
Os_Hal_UnhandledInterruptEntry(4, 123)
Os_Hal_UnhandledInterruptEntry(4, 124)
Os_Hal_UnhandledInterruptEntry(4, 125)
Os_Hal_UnhandledInterruptEntry(4, 126)
Os_Hal_UnhandledInterruptEntry(4, 127)
Os_Hal_UnhandledInterruptEntry(4, 128)
Os_Hal_UnhandledInterruptEntry(4, 129)
Os_Hal_UnhandledInterruptEntry(4, 130)
Os_Hal_UnhandledInterruptEntry(4, 131)
Os_Hal_UnhandledInterruptEntry(4, 132)
Os_Hal_UnhandledInterruptEntry(4, 133)
Os_Hal_UnhandledInterruptEntry(4, 134)
Os_Hal_UnhandledInterruptEntry(4, 135)
Os_Hal_UnhandledInterruptEntry(4, 136)
Os_Hal_UnhandledInterruptEntry(4, 137)
Os_Hal_UnhandledInterruptEntry(4, 138)
Os_Hal_UnhandledInterruptEntry(4, 139)
Os_Hal_UnhandledInterruptEntry(4, 140)
Os_Hal_UnhandledInterruptEntry(4, 141)
Os_Hal_UnhandledInterruptEntry(4, 142)
Os_Hal_UnhandledInterruptEntry(4, 143)
Os_Hal_UnhandledInterruptEntry(4, 144)
Os_Hal_UnhandledInterruptEntry(4, 145)
Os_Hal_UnhandledInterruptEntry(4, 146)
Os_Hal_UnhandledInterruptEntry(4, 147)
Os_Hal_UnhandledInterruptEntry(4, 148)
Os_Hal_UnhandledInterruptEntry(4, 149)
Os_Hal_UnhandledInterruptEntry(4, 150)
Os_Hal_UnhandledInterruptEntry(4, 151)
Os_Hal_UnhandledInterruptEntry(4, 152)
Os_Hal_UnhandledInterruptEntry(4, 153)
Os_Hal_UnhandledInterruptEntry(4, 154)
Os_Hal_UnhandledInterruptEntry(4, 155)
Os_Hal_UnhandledInterruptEntry(4, 156)
Os_Hal_UnhandledInterruptEntry(4, 157)
Os_Hal_UnhandledInterruptEntry(4, 158)
Os_Hal_UnhandledInterruptEntry(4, 159)
Os_Hal_UnhandledInterruptEntry(4, 160)
Os_Hal_UnhandledInterruptEntry(4, 161)
Os_Hal_UnhandledInterruptEntry(4, 162)
Os_Hal_UnhandledInterruptEntry(4, 163)
Os_Hal_UnhandledInterruptEntry(4, 164)
Os_Hal_UnhandledInterruptEntry(4, 165)
Os_Hal_UnhandledInterruptEntry(4, 166)
Os_Hal_UnhandledInterruptEntry(4, 167)
Os_Hal_UnhandledInterruptEntry(4, 168)
Os_Hal_UnhandledInterruptEntry(4, 169)
Os_Hal_UnhandledInterruptEntry(4, 170)
Os_Hal_UnhandledInterruptEntry(4, 171)
Os_Hal_UnhandledInterruptEntry(4, 172)
Os_Hal_UnhandledInterruptEntry(4, 173)
Os_Hal_UnhandledInterruptEntry(4, 174)
Os_Hal_UnhandledInterruptEntry(4, 175)
Os_Hal_UnhandledInterruptEntry(4, 176)
Os_Hal_UnhandledInterruptEntry(4, 177)
Os_Hal_UnhandledInterruptEntry(4, 178)
Os_Hal_UnhandledInterruptEntry(4, 179)
Os_Hal_UnhandledInterruptEntry(4, 180)
Os_Hal_UnhandledInterruptEntry(4, 181)
Os_Hal_UnhandledInterruptEntry(4, 182)
Os_Hal_UnhandledInterruptEntry(4, 183)
Os_Hal_UnhandledInterruptEntry(4, 184)
Os_Hal_UnhandledInterruptEntry(4, 185)
Os_Hal_UnhandledInterruptEntry(4, 186)
Os_Hal_UnhandledInterruptEntry(4, 187)
Os_Hal_UnhandledInterruptEntry(4, 188)
Os_Hal_UnhandledInterruptEntry(4, 189)
Os_Hal_UnhandledInterruptEntry(4, 190)
Os_Hal_UnhandledInterruptEntry(4, 191)
Os_Hal_UnhandledInterruptEntry(4, 192)
Os_Hal_UnhandledInterruptEntry(4, 193)
Os_Hal_UnhandledInterruptEntry(4, 194)
Os_Hal_UnhandledInterruptEntry(4, 195)
Os_Hal_UnhandledInterruptEntry(4, 196)
Os_Hal_UnhandledInterruptEntry(4, 197)
Os_Hal_UnhandledInterruptEntry(4, 198)
Os_Hal_UnhandledInterruptEntry(4, 199)
Os_Hal_UnhandledInterruptEntry(4, 200)
Os_Hal_UnhandledInterruptEntry(4, 201)
Os_Hal_UnhandledInterruptEntry(4, 202)
Os_Hal_UnhandledInterruptEntry(4, 203)
Os_Hal_UnhandledInterruptEntry(4, 204)
Os_Hal_UnhandledInterruptEntry(4, 205)
Os_Hal_UnhandledInterruptEntry(4, 206)
Os_Hal_UnhandledInterruptEntry(4, 207)
Os_Hal_UnhandledInterruptEntry(4, 208)
Os_Hal_UnhandledInterruptEntry(4, 209)
Os_Hal_UnhandledInterruptEntry(4, 210)
Os_Hal_UnhandledInterruptEntry(4, 211)
Os_Hal_UnhandledInterruptEntry(4, 212)
Os_Hal_UnhandledInterruptEntry(4, 213)
Os_Hal_UnhandledInterruptEntry(4, 214)
Os_Hal_UnhandledInterruptEntry(4, 215)
Os_Hal_UnhandledInterruptEntry(4, 216)
Os_Hal_UnhandledInterruptEntry(4, 217)
Os_Hal_UnhandledInterruptEntry(4, 218)
Os_Hal_UnhandledInterruptEntry(4, 219)
Os_Hal_UnhandledInterruptEntry(4, 220)
Os_Hal_UnhandledInterruptEntry(4, 221)
Os_Hal_UnhandledInterruptEntry(4, 222)
Os_Hal_UnhandledInterruptEntry(4, 223)
Os_Hal_UnhandledInterruptEntry(4, 224)
Os_Hal_UnhandledInterruptEntry(4, 225)
Os_Hal_UnhandledInterruptEntry(4, 226)
Os_Hal_UnhandledInterruptEntry(4, 227)
Os_Hal_UnhandledInterruptEntry(4, 228)
Os_Hal_UnhandledInterruptEntry(4, 229)
Os_Hal_UnhandledInterruptEntry(4, 230)
Os_Hal_UnhandledInterruptEntry(4, 231)
Os_Hal_UnhandledInterruptEntry(4, 232)
Os_Hal_UnhandledInterruptEntry(4, 233)
Os_Hal_UnhandledInterruptEntry(4, 234)
Os_Hal_UnhandledInterruptEntry(4, 235)
Os_Hal_UnhandledInterruptEntry(4, 236)
Os_Hal_UnhandledInterruptEntry(4, 237)
Os_Hal_UnhandledInterruptEntry(4, 238)
Os_Hal_UnhandledInterruptEntry(4, 239)
Os_Hal_UnhandledInterruptEntry(4, 240)
Os_Hal_UnhandledInterruptEntry(4, 241)
Os_Hal_UnhandledInterruptEntry(4, 242)
Os_Hal_UnhandledInterruptEntry(4, 243)
Os_Hal_UnhandledInterruptEntry(4, 244)
Os_Hal_UnhandledInterruptEntry(4, 245)
Os_Hal_UnhandledInterruptEntry(4, 246)
Os_Hal_UnhandledInterruptEntry(4, 247)
Os_Hal_UnhandledInterruptEntry(4, 248)
Os_Hal_UnhandledInterruptEntry(4, 249)
Os_Hal_UnhandledInterruptEntry(4, 250)
Os_Hal_UnhandledInterruptEntry(4, 251)
Os_Hal_UnhandledInterruptEntry(4, 252)
Os_Hal_UnhandledInterruptEntry(4, 253)
Os_Hal_UnhandledInterruptEntry(4, 254)
Os_Hal_UnhandledInterruptEntry(4, 255)

#define OS_STOP_SEC_INTVEC_CORE4_CODE
#include "Os_MemMap_OsSections.h" /* PRQA S 5087 */ /* MD_MSR_MemMap */


/**********************************************************************************************************************
 *  EXCEPTION VECTOR TABLE CORE 5
 *********************************************************************************************************************/

#define OS_START_SEC_EXCVEC_CORE5_CODE
#include "Os_MemMap_OsSections.h" /* PRQA S 5087 */ /* MD_MSR_MemMap */

Os_Hal_UnhandledTrapEntry(5, 0)
Os_Hal_UnhandledTrapEntry(5, 1)
Os_Hal_UnhandledTrapEntry(5, 2)
Os_Hal_UnhandledTrapEntry(5, 3)
Os_Hal_UnhandledTrapEntry(5, 4)
Os_Hal_UnhandledTrapEntry(5, 5)
Os_Hal_UnhandledTrapEntry(5, 6)
Os_Hal_UnhandledTrapEntry(5, 7)

#define OS_STOP_SEC_EXCVEC_CORE5_CODE
#include "Os_MemMap_OsSections.h" /* PRQA S 5087 */ /* MD_MSR_MemMap */


/**********************************************************************************************************************
 *  INTERRUPT VECTOR TABLE CORE 5
 *********************************************************************************************************************/

#define OS_START_SEC_INTVEC_CORE5_CODE
#include "Os_MemMap_OsSections.h" /* PRQA S 5087 */ /* MD_MSR_MemMap */

Os_Hal_UnhandledInterruptEntry(5, 0)
Os_Hal_UnhandledInterruptEntry(5, 1)
Os_Hal_UnhandledInterruptEntry(5, 2)
Os_Hal_UnhandledInterruptEntry(5, 3)
Os_Hal_UnhandledInterruptEntry(5, 4)
Os_Hal_UnhandledInterruptEntry(5, 5)
Os_Hal_UnhandledInterruptEntry(5, 6)
Os_Hal_UnhandledInterruptEntry(5, 7)
Os_Hal_UnhandledInterruptEntry(5, 8)
Os_Hal_UnhandledInterruptEntry(5, 9)
Os_Hal_UnhandledInterruptEntry(5, 10)
Os_Hal_UnhandledInterruptEntry(5, 11)
Os_Hal_UnhandledInterruptEntry(5, 12)
Os_Hal_UnhandledInterruptEntry(5, 13)
Os_Hal_UnhandledInterruptEntry(5, 14)
Os_Hal_UnhandledInterruptEntry(5, 15)
Os_Hal_UnhandledInterruptEntry(5, 16)
Os_Hal_UnhandledInterruptEntry(5, 17)
Os_Hal_Cat2InterruptEntry(5, 18, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_XSignalIsr_OsCore5)
Os_Hal_UnhandledInterruptEntry(5, 19)
Os_Hal_Cat2InterruptEntry(5, 20, OS_CFG_HAL_ISR2_DISABLE_LEVEL, OsCfg_Isr_CounterIsr_SystemTimer5)
Os_Hal_UnhandledInterruptEntry(5, 21)
Os_Hal_UnhandledInterruptEntry(5, 22)
Os_Hal_UnhandledInterruptEntry(5, 23)
Os_Hal_UnhandledInterruptEntry(5, 24)
Os_Hal_UnhandledInterruptEntry(5, 25)
Os_Hal_UnhandledInterruptEntry(5, 26)
Os_Hal_UnhandledInterruptEntry(5, 27)
Os_Hal_UnhandledInterruptEntry(5, 28)
Os_Hal_UnhandledInterruptEntry(5, 29)
Os_Hal_UnhandledInterruptEntry(5, 30)
Os_Hal_UnhandledInterruptEntry(5, 31)
Os_Hal_UnhandledInterruptEntry(5, 32)
Os_Hal_UnhandledInterruptEntry(5, 33)
Os_Hal_UnhandledInterruptEntry(5, 34)
Os_Hal_UnhandledInterruptEntry(5, 35)
Os_Hal_UnhandledInterruptEntry(5, 36)
Os_Hal_UnhandledInterruptEntry(5, 37)
Os_Hal_UnhandledInterruptEntry(5, 38)
Os_Hal_UnhandledInterruptEntry(5, 39)
Os_Hal_UnhandledInterruptEntry(5, 40)
Os_Hal_UnhandledInterruptEntry(5, 41)
Os_Hal_UnhandledInterruptEntry(5, 42)
Os_Hal_UnhandledInterruptEntry(5, 43)
Os_Hal_UnhandledInterruptEntry(5, 44)
Os_Hal_UnhandledInterruptEntry(5, 45)
Os_Hal_UnhandledInterruptEntry(5, 46)
Os_Hal_UnhandledInterruptEntry(5, 47)
Os_Hal_UnhandledInterruptEntry(5, 48)
Os_Hal_UnhandledInterruptEntry(5, 49)
Os_Hal_UnhandledInterruptEntry(5, 50)
Os_Hal_UnhandledInterruptEntry(5, 51)
Os_Hal_UnhandledInterruptEntry(5, 52)
Os_Hal_UnhandledInterruptEntry(5, 53)
Os_Hal_UnhandledInterruptEntry(5, 54)
Os_Hal_UnhandledInterruptEntry(5, 55)
Os_Hal_UnhandledInterruptEntry(5, 56)
Os_Hal_UnhandledInterruptEntry(5, 57)
Os_Hal_UnhandledInterruptEntry(5, 58)
Os_Hal_UnhandledInterruptEntry(5, 59)
Os_Hal_UnhandledInterruptEntry(5, 60)
Os_Hal_UnhandledInterruptEntry(5, 61)
Os_Hal_UnhandledInterruptEntry(5, 62)
Os_Hal_UnhandledInterruptEntry(5, 63)
Os_Hal_UnhandledInterruptEntry(5, 64)
Os_Hal_UnhandledInterruptEntry(5, 65)
Os_Hal_UnhandledInterruptEntry(5, 66)
Os_Hal_UnhandledInterruptEntry(5, 67)
Os_Hal_UnhandledInterruptEntry(5, 68)
Os_Hal_UnhandledInterruptEntry(5, 69)
Os_Hal_UnhandledInterruptEntry(5, 70)
Os_Hal_UnhandledInterruptEntry(5, 71)
Os_Hal_UnhandledInterruptEntry(5, 72)
Os_Hal_UnhandledInterruptEntry(5, 73)
Os_Hal_UnhandledInterruptEntry(5, 74)
Os_Hal_UnhandledInterruptEntry(5, 75)
Os_Hal_UnhandledInterruptEntry(5, 76)
Os_Hal_UnhandledInterruptEntry(5, 77)
Os_Hal_UnhandledInterruptEntry(5, 78)
Os_Hal_UnhandledInterruptEntry(5, 79)
Os_Hal_UnhandledInterruptEntry(5, 80)
Os_Hal_UnhandledInterruptEntry(5, 81)
Os_Hal_UnhandledInterruptEntry(5, 82)
Os_Hal_UnhandledInterruptEntry(5, 83)
Os_Hal_UnhandledInterruptEntry(5, 84)
Os_Hal_UnhandledInterruptEntry(5, 85)
Os_Hal_UnhandledInterruptEntry(5, 86)
Os_Hal_UnhandledInterruptEntry(5, 87)
Os_Hal_UnhandledInterruptEntry(5, 88)
Os_Hal_UnhandledInterruptEntry(5, 89)
Os_Hal_UnhandledInterruptEntry(5, 90)
Os_Hal_UnhandledInterruptEntry(5, 91)
Os_Hal_UnhandledInterruptEntry(5, 92)
Os_Hal_UnhandledInterruptEntry(5, 93)
Os_Hal_UnhandledInterruptEntry(5, 94)
Os_Hal_UnhandledInterruptEntry(5, 95)
Os_Hal_UnhandledInterruptEntry(5, 96)
Os_Hal_UnhandledInterruptEntry(5, 97)
Os_Hal_UnhandledInterruptEntry(5, 98)
Os_Hal_UnhandledInterruptEntry(5, 99)
Os_Hal_UnhandledInterruptEntry(5, 100)
Os_Hal_UnhandledInterruptEntry(5, 101)
Os_Hal_UnhandledInterruptEntry(5, 102)
Os_Hal_UnhandledInterruptEntry(5, 103)
Os_Hal_UnhandledInterruptEntry(5, 104)
Os_Hal_UnhandledInterruptEntry(5, 105)
Os_Hal_UnhandledInterruptEntry(5, 106)
Os_Hal_UnhandledInterruptEntry(5, 107)
Os_Hal_UnhandledInterruptEntry(5, 108)
Os_Hal_UnhandledInterruptEntry(5, 109)
Os_Hal_UnhandledInterruptEntry(5, 110)
Os_Hal_UnhandledInterruptEntry(5, 111)
Os_Hal_UnhandledInterruptEntry(5, 112)
Os_Hal_UnhandledInterruptEntry(5, 113)
Os_Hal_UnhandledInterruptEntry(5, 114)
Os_Hal_UnhandledInterruptEntry(5, 115)
Os_Hal_UnhandledInterruptEntry(5, 116)
Os_Hal_UnhandledInterruptEntry(5, 117)
Os_Hal_UnhandledInterruptEntry(5, 118)
Os_Hal_UnhandledInterruptEntry(5, 119)
Os_Hal_UnhandledInterruptEntry(5, 120)
Os_Hal_UnhandledInterruptEntry(5, 121)
Os_Hal_UnhandledInterruptEntry(5, 122)
Os_Hal_UnhandledInterruptEntry(5, 123)
Os_Hal_UnhandledInterruptEntry(5, 124)
Os_Hal_UnhandledInterruptEntry(5, 125)
Os_Hal_UnhandledInterruptEntry(5, 126)
Os_Hal_UnhandledInterruptEntry(5, 127)
Os_Hal_UnhandledInterruptEntry(5, 128)
Os_Hal_UnhandledInterruptEntry(5, 129)
Os_Hal_UnhandledInterruptEntry(5, 130)
Os_Hal_UnhandledInterruptEntry(5, 131)
Os_Hal_UnhandledInterruptEntry(5, 132)
Os_Hal_UnhandledInterruptEntry(5, 133)
Os_Hal_UnhandledInterruptEntry(5, 134)
Os_Hal_UnhandledInterruptEntry(5, 135)
Os_Hal_UnhandledInterruptEntry(5, 136)
Os_Hal_UnhandledInterruptEntry(5, 137)
Os_Hal_UnhandledInterruptEntry(5, 138)
Os_Hal_UnhandledInterruptEntry(5, 139)
Os_Hal_UnhandledInterruptEntry(5, 140)
Os_Hal_UnhandledInterruptEntry(5, 141)
Os_Hal_UnhandledInterruptEntry(5, 142)
Os_Hal_UnhandledInterruptEntry(5, 143)
Os_Hal_UnhandledInterruptEntry(5, 144)
Os_Hal_UnhandledInterruptEntry(5, 145)
Os_Hal_UnhandledInterruptEntry(5, 146)
Os_Hal_UnhandledInterruptEntry(5, 147)
Os_Hal_UnhandledInterruptEntry(5, 148)
Os_Hal_UnhandledInterruptEntry(5, 149)
Os_Hal_UnhandledInterruptEntry(5, 150)
Os_Hal_UnhandledInterruptEntry(5, 151)
Os_Hal_UnhandledInterruptEntry(5, 152)
Os_Hal_UnhandledInterruptEntry(5, 153)
Os_Hal_UnhandledInterruptEntry(5, 154)
Os_Hal_UnhandledInterruptEntry(5, 155)
Os_Hal_UnhandledInterruptEntry(5, 156)
Os_Hal_UnhandledInterruptEntry(5, 157)
Os_Hal_UnhandledInterruptEntry(5, 158)
Os_Hal_UnhandledInterruptEntry(5, 159)
Os_Hal_UnhandledInterruptEntry(5, 160)
Os_Hal_UnhandledInterruptEntry(5, 161)
Os_Hal_UnhandledInterruptEntry(5, 162)
Os_Hal_UnhandledInterruptEntry(5, 163)
Os_Hal_UnhandledInterruptEntry(5, 164)
Os_Hal_UnhandledInterruptEntry(5, 165)
Os_Hal_UnhandledInterruptEntry(5, 166)
Os_Hal_UnhandledInterruptEntry(5, 167)
Os_Hal_UnhandledInterruptEntry(5, 168)
Os_Hal_UnhandledInterruptEntry(5, 169)
Os_Hal_UnhandledInterruptEntry(5, 170)
Os_Hal_UnhandledInterruptEntry(5, 171)
Os_Hal_UnhandledInterruptEntry(5, 172)
Os_Hal_UnhandledInterruptEntry(5, 173)
Os_Hal_UnhandledInterruptEntry(5, 174)
Os_Hal_UnhandledInterruptEntry(5, 175)
Os_Hal_UnhandledInterruptEntry(5, 176)
Os_Hal_UnhandledInterruptEntry(5, 177)
Os_Hal_UnhandledInterruptEntry(5, 178)
Os_Hal_UnhandledInterruptEntry(5, 179)
Os_Hal_UnhandledInterruptEntry(5, 180)
Os_Hal_UnhandledInterruptEntry(5, 181)
Os_Hal_UnhandledInterruptEntry(5, 182)
Os_Hal_UnhandledInterruptEntry(5, 183)
Os_Hal_UnhandledInterruptEntry(5, 184)
Os_Hal_UnhandledInterruptEntry(5, 185)
Os_Hal_UnhandledInterruptEntry(5, 186)
Os_Hal_UnhandledInterruptEntry(5, 187)
Os_Hal_UnhandledInterruptEntry(5, 188)
Os_Hal_UnhandledInterruptEntry(5, 189)
Os_Hal_UnhandledInterruptEntry(5, 190)
Os_Hal_UnhandledInterruptEntry(5, 191)
Os_Hal_UnhandledInterruptEntry(5, 192)
Os_Hal_UnhandledInterruptEntry(5, 193)
Os_Hal_UnhandledInterruptEntry(5, 194)
Os_Hal_UnhandledInterruptEntry(5, 195)
Os_Hal_UnhandledInterruptEntry(5, 196)
Os_Hal_UnhandledInterruptEntry(5, 197)
Os_Hal_UnhandledInterruptEntry(5, 198)
Os_Hal_UnhandledInterruptEntry(5, 199)
Os_Hal_UnhandledInterruptEntry(5, 200)
Os_Hal_UnhandledInterruptEntry(5, 201)
Os_Hal_UnhandledInterruptEntry(5, 202)
Os_Hal_UnhandledInterruptEntry(5, 203)
Os_Hal_UnhandledInterruptEntry(5, 204)
Os_Hal_UnhandledInterruptEntry(5, 205)
Os_Hal_UnhandledInterruptEntry(5, 206)
Os_Hal_UnhandledInterruptEntry(5, 207)
Os_Hal_UnhandledInterruptEntry(5, 208)
Os_Hal_UnhandledInterruptEntry(5, 209)
Os_Hal_UnhandledInterruptEntry(5, 210)
Os_Hal_UnhandledInterruptEntry(5, 211)
Os_Hal_UnhandledInterruptEntry(5, 212)
Os_Hal_UnhandledInterruptEntry(5, 213)
Os_Hal_UnhandledInterruptEntry(5, 214)
Os_Hal_UnhandledInterruptEntry(5, 215)
Os_Hal_UnhandledInterruptEntry(5, 216)
Os_Hal_UnhandledInterruptEntry(5, 217)
Os_Hal_UnhandledInterruptEntry(5, 218)
Os_Hal_UnhandledInterruptEntry(5, 219)
Os_Hal_UnhandledInterruptEntry(5, 220)
Os_Hal_UnhandledInterruptEntry(5, 221)
Os_Hal_UnhandledInterruptEntry(5, 222)
Os_Hal_UnhandledInterruptEntry(5, 223)
Os_Hal_UnhandledInterruptEntry(5, 224)
Os_Hal_UnhandledInterruptEntry(5, 225)
Os_Hal_UnhandledInterruptEntry(5, 226)
Os_Hal_UnhandledInterruptEntry(5, 227)
Os_Hal_UnhandledInterruptEntry(5, 228)
Os_Hal_UnhandledInterruptEntry(5, 229)
Os_Hal_UnhandledInterruptEntry(5, 230)
Os_Hal_UnhandledInterruptEntry(5, 231)
Os_Hal_UnhandledInterruptEntry(5, 232)
Os_Hal_UnhandledInterruptEntry(5, 233)
Os_Hal_UnhandledInterruptEntry(5, 234)
Os_Hal_UnhandledInterruptEntry(5, 235)
Os_Hal_UnhandledInterruptEntry(5, 236)
Os_Hal_UnhandledInterruptEntry(5, 237)
Os_Hal_UnhandledInterruptEntry(5, 238)
Os_Hal_UnhandledInterruptEntry(5, 239)
Os_Hal_UnhandledInterruptEntry(5, 240)
Os_Hal_UnhandledInterruptEntry(5, 241)
Os_Hal_UnhandledInterruptEntry(5, 242)
Os_Hal_UnhandledInterruptEntry(5, 243)
Os_Hal_UnhandledInterruptEntry(5, 244)
Os_Hal_UnhandledInterruptEntry(5, 245)
Os_Hal_UnhandledInterruptEntry(5, 246)
Os_Hal_UnhandledInterruptEntry(5, 247)
Os_Hal_UnhandledInterruptEntry(5, 248)
Os_Hal_UnhandledInterruptEntry(5, 249)
Os_Hal_UnhandledInterruptEntry(5, 250)
Os_Hal_UnhandledInterruptEntry(5, 251)
Os_Hal_UnhandledInterruptEntry(5, 252)
Os_Hal_UnhandledInterruptEntry(5, 253)
Os_Hal_UnhandledInterruptEntry(5, 254)
Os_Hal_UnhandledInterruptEntry(5, 255)

#define OS_STOP_SEC_INTVEC_CORE5_CODE
#include "Os_MemMap_OsSections.h" /* PRQA S 5087 */ /* MD_MSR_MemMap */


/**********************************************************************************************************************
 *  END OF FILE: Os_Hal_Entry_Lcfg.c
 *********************************************************************************************************************/
