/**********************************************************************************************************************
 *  COPYRIGHT
 *  -------------------------------------------------------------------------------------------------------------------
 *
 *                This software is copyright protected and proprietary to Vector Informatik GmbH.
 *                Vector Informatik GmbH grants to you only those rights as set out in the license conditions.
 *                All other rights remain with Vector Informatik GmbH.
 *  -------------------------------------------------------------------------------------------------------------------
 *  FILE DESCRIPTION
 *  -------------------------------------------------------------------------------------------------------------------
 *          File:  Rte_Hook.h
 *        Config:  Bsw_Project.dpa
 *   ECU-Project:  MDA
 *
 *     Generator:  MICROSAR RTE Generator Version 4.19.0
 *                 RTE Core Version 1.19.0
 *       License:  CBD1900078
 *
 *   Description:  Header file containing definitions for VFB tracing
 *********************************************************************************************************************/


/**********************************************************************************************************************
 * Names of available VFB-Trace-Hooks
 **********************************************************************************************************************
 *
 * Not configured:
 *
 *  Rte_CallHook_CtMDA_Control_Logic_PoPT2000_Ctrl_PT2000_Enable_mode_Return
 *  Rte_CallHook_CtMDA_Control_Logic_PoPT2000_Ctrl_PT2000_Enable_mode_Start
 *  Rte_CallHook_CtMDA_Control_Logic_PoPT2000_Ctrl_PT2000_Init_Return
 *  Rte_CallHook_CtMDA_Control_Logic_PoPT2000_Ctrl_PT2000_Init_Start
 *  Rte_CallHook_CtMDA_Control_Logic_PoPT2000_Ctrl_PT2000_Mode_Change_Return
 *  Rte_CallHook_CtMDA_Control_Logic_PoPT2000_Ctrl_PT2000_Mode_Change_Start
 *  Rte_CallHook_CtMDA_Control_Logic_PoPT2000_Ctrl_Set_ConstantCurrent_Return
 *  Rte_CallHook_CtMDA_Control_Logic_PoPT2000_Ctrl_Set_ConstantCurrent_Start
 *  Rte_CallHook_CtMDA_Control_Logic_PoPT2000_Ctrl_Set_Peak_Hold_Return
 *  Rte_CallHook_CtMDA_Control_Logic_PoPT2000_Ctrl_Set_Peak_Hold_Start
 *  Rte_ReadHook_BswM_Request_ESH_PostRunRequest_0_requestedMode_Return
 *  Rte_ReadHook_BswM_Request_ESH_PostRunRequest_0_requestedMode_Start
 *  Rte_ReadHook_BswM_Request_ESH_PostRunRequest_1_requestedMode_Return
 *  Rte_ReadHook_BswM_Request_ESH_PostRunRequest_1_requestedMode_Start
 *  Rte_ReadHook_BswM_Request_ESH_RunRequest_0_requestedMode_Return
 *  Rte_ReadHook_BswM_Request_ESH_RunRequest_0_requestedMode_Start
 *  Rte_ReadHook_BswM_Request_ESH_RunRequest_1_requestedMode_Return
 *  Rte_ReadHook_BswM_Request_ESH_RunRequest_1_requestedMode_Start
 *  Rte_ReadHook_CtMDA_Control_Logic_PpBodyAccZ_BodyAcc_Return
 *  Rte_ReadHook_CtMDA_Control_Logic_PpBodyAccZ_BodyAcc_Start
 *  Rte_ReadHook_CtMDA_Control_Logic_PpIMU_IMUAcc_Return
 *  Rte_ReadHook_CtMDA_Control_Logic_PpIMU_IMUAcc_Start
 *  Rte_ReadHook_CtMDA_Control_Logic_PpIMU_IMUAngle_Return
 *  Rte_ReadHook_CtMDA_Control_Logic_PpIMU_IMUAngle_Start
 *  Rte_ReadHook_CtMDA_Control_Logic_PpIMU_IMURate_Return
 *  Rte_ReadHook_CtMDA_Control_Logic_PpIMU_IMURate_Start
 *  Rte_ReadHook_CtMDA_Control_Logic_PpIMU_IMUVel_Return
 *  Rte_ReadHook_CtMDA_Control_Logic_PpIMU_IMUVel_Start
 *  Rte_ReadHook_CtMDA_Control_Logic_PpMotFLAct_MotFLAct_Return
 *  Rte_ReadHook_CtMDA_Control_Logic_PpMotFLAct_MotFLAct_Start
 *  Rte_ReadHook_CtMDA_Control_Logic_PpMotFRAct_MotFRAct_Return
 *  Rte_ReadHook_CtMDA_Control_Logic_PpMotFRAct_MotFRAct_Start
 *  Rte_ReadHook_CtMDA_Control_Logic_PpMotRLAct_MotRLAct_Return
 *  Rte_ReadHook_CtMDA_Control_Logic_PpMotRLAct_MotRLAct_Start
 *  Rte_ReadHook_CtMDA_Control_Logic_PpMotRRAct_MotRRAct_Return
 *  Rte_ReadHook_CtMDA_Control_Logic_PpMotRRAct_MotRRAct_Start
 *  Rte_ReadHook_CtMDA_Control_Logic_PpPedlPos_PedlPos_Return
 *  Rte_ReadHook_CtMDA_Control_Logic_PpPedlPos_PedlPos_Start
 *  Rte_ReadHook_CtMDA_Control_Logic_PpPressure_Pressure_Return
 *  Rte_ReadHook_CtMDA_Control_Logic_PpPressure_Pressure_Start
 *  Rte_ReadHook_CtMDA_Control_Logic_PpSteerWhl_SteerWhl_Return
 *  Rte_ReadHook_CtMDA_Control_Logic_PpSteerWhl_SteerWhl_Start
 *  Rte_ReadHook_CtMDA_Control_Logic_PpSuspHeight_SuspHeight_Return
 *  Rte_ReadHook_CtMDA_Control_Logic_PpSuspHeight_SuspHeight_Start
 *  Rte_ReadHook_CtMDA_Control_Logic_PpVelFbAll_VlvFL_Return
 *  Rte_ReadHook_CtMDA_Control_Logic_PpVelFbAll_VlvFL_Start
 *  Rte_ReadHook_CtMDA_Control_Logic_PpVelFbAll_VlvFR_Return
 *  Rte_ReadHook_CtMDA_Control_Logic_PpVelFbAll_VlvFR_Start
 *  Rte_ReadHook_CtMDA_Control_Logic_PpVelFbAll_VlvRL_Return
 *  Rte_ReadHook_CtMDA_Control_Logic_PpVelFbAll_VlvRL_Start
 *  Rte_ReadHook_CtMDA_Control_Logic_PpVelFbAll_VlvRR_Return
 *  Rte_ReadHook_CtMDA_Control_Logic_PpVelFbAll_VlvRR_Start
 *  Rte_ReadHook_CtMDA_Control_Logic_PpWhlAccZ_WhlAcc_Return
 *  Rte_ReadHook_CtMDA_Control_Logic_PpWhlAccZ_WhlAcc_Start
 *  Rte_ReadHook_CtMotor_FL_PpMotTgtOutFL_MotTgtOutFL_Return
 *  Rte_ReadHook_CtMotor_FL_PpMotTgtOutFL_MotTgtOutFL_Start
 *  Rte_ReadHook_CtMotor_FR_PpMotTgtOutFR_MotTgtOutFR_Return
 *  Rte_ReadHook_CtMotor_FR_PpMotTgtOutFR_MotTgtOutFR_Start
 *  Rte_ReadHook_CtMotor_RL_PpMotTgtOutRL_MotTgtOutRL_Return
 *  Rte_ReadHook_CtMotor_RL_PpMotTgtOutRL_MotTgtOutRL_Start
 *  Rte_ReadHook_CtMotor_RR_PpMotTgtOutRR_MotTgtOutRR_Return
 *  Rte_ReadHook_CtMotor_RR_PpMotTgtOutRR_MotTgtOutRR_Start
 *  Rte_ReadHook_CtPT2000_Handler_PpVlvTgtCCFF_VlvTgtChannel_Return
 *  Rte_ReadHook_CtPT2000_Handler_PpVlvTgtCCFF_VlvTgtChannel_Start
 *  Rte_ReadHook_CtPT2000_Handler_PpVlvTgtCCFF_VlvTgtCurrent_Return
 *  Rte_ReadHook_CtPT2000_Handler_PpVlvTgtCCFF_VlvTgtCurrent_Start
 *  Rte_ReadHook_CtPT2000_Handler_PpVlvTgtCCFF_VlvTgtFlutter_Return
 *  Rte_ReadHook_CtPT2000_Handler_PpVlvTgtCCFF_VlvTgtFlutter_Start
 *  Rte_ReadHook_CtPT2000_Handler_PpVlvTgtCCFF_VlvTgtFrequency_Return
 *  Rte_ReadHook_CtPT2000_Handler_PpVlvTgtCCFF_VlvTgtFrequency_Start
 *  Rte_Runnable_BswM_BswM_MainFunction_Return
 *  Rte_Runnable_BswM_BswM_MainFunction_Start
 *  Rte_Runnable_ComM_ComM_MainFunction_0_Return
 *  Rte_Runnable_ComM_ComM_MainFunction_0_Start
 *  Rte_Runnable_ComM_ComM_MainFunction_1_Return
 *  Rte_Runnable_ComM_ComM_MainFunction_1_Start
 *  Rte_Runnable_ComM_ComM_MainFunction_2_Return
 *  Rte_Runnable_ComM_ComM_MainFunction_2_Start
 *  Rte_Runnable_ComM_ComM_MainFunction_3_Return
 *  Rte_Runnable_ComM_ComM_MainFunction_3_Start
 *  Rte_Runnable_ComM_ComM_MainFunction_4_Return
 *  Rte_Runnable_ComM_ComM_MainFunction_4_Start
 *  Rte_Runnable_ComM_ComM_MainFunction_5_Return
 *  Rte_Runnable_ComM_ComM_MainFunction_5_Start
 *  Rte_Runnable_ComM_GetCurrentComMode_Return
 *  Rte_Runnable_ComM_GetCurrentComMode_Start
 *  Rte_Runnable_ComM_GetInhibitionStatus_Return
 *  Rte_Runnable_ComM_GetInhibitionStatus_Start
 *  Rte_Runnable_ComM_GetMaxComMode_Return
 *  Rte_Runnable_ComM_GetMaxComMode_Start
 *  Rte_Runnable_ComM_GetRequestedComMode_Return
 *  Rte_Runnable_ComM_GetRequestedComMode_Start
 *  Rte_Runnable_ComM_LimitChannelToNoComMode_Return
 *  Rte_Runnable_ComM_LimitChannelToNoComMode_Start
 *  Rte_Runnable_ComM_LimitECUToNoComMode_Return
 *  Rte_Runnable_ComM_LimitECUToNoComMode_Start
 *  Rte_Runnable_ComM_PreventWakeUp_Return
 *  Rte_Runnable_ComM_PreventWakeUp_Start
 *  Rte_Runnable_ComM_ReadInhibitCounter_Return
 *  Rte_Runnable_ComM_ReadInhibitCounter_Start
 *  Rte_Runnable_ComM_RequestComMode_Return
 *  Rte_Runnable_ComM_RequestComMode_Start
 *  Rte_Runnable_ComM_ResetInhibitCounter_Return
 *  Rte_Runnable_ComM_ResetInhibitCounter_Start
 *  Rte_Runnable_ComM_SetECUGroupClassification_Return
 *  Rte_Runnable_ComM_SetECUGroupClassification_Start
 *  Rte_Runnable_Core5swc_Runnable_Return
 *  Rte_Runnable_Core5swc_Runnable_Start
 *  Rte_Runnable_CtCDD_CtCDD_Return
 *  Rte_Runnable_CtCDD_CtCDD_Start
 *  Rte_Runnable_CtIoHardWare_Adc_Write_Return
 *  Rte_Runnable_CtIoHardWare_Adc_Write_Start
 *  Rte_Runnable_CtMDA_Control_Logic_MDA_Control_Logic_Return
 *  Rte_Runnable_CtMDA_Control_Logic_MDA_Control_Logic_Start
 *  Rte_Runnable_CtMotor_FL_CpApMotor_FL_Return
 *  Rte_Runnable_CtMotor_FL_CpApMotor_FL_Start
 *  Rte_Runnable_CtMotor_FR_CpApMotor_FR_Return
 *  Rte_Runnable_CtMotor_FR_CpApMotor_FR_Start
 *  Rte_Runnable_CtMotor_RL_CpApMotor_RL_Return
 *  Rte_Runnable_CtMotor_RL_CpApMotor_RL_Start
 *  Rte_Runnable_CtMotor_RR_CpApMotor_RR_Return
 *  Rte_Runnable_CtMotor_RR_CpApMotor_RR_Start
 *  Rte_Runnable_CtPSI5_Handler_PSI5MAIN_HD_Return
 *  Rte_Runnable_CtPSI5_Handler_PSI5MAIN_HD_Start
 *  Rte_Runnable_CtPT2000_Handler_PT2000_Diag_HD_Return
 *  Rte_Runnable_CtPT2000_Handler_PT2000_Diag_HD_Start
 *  Rte_Runnable_CtPT2000_Handler_PT2000_Main_HD_Return
 *  Rte_Runnable_CtPT2000_Handler_PT2000_Main_HD_Start
 *  Rte_Runnable_CtPT2000_Handler_PoPT2000_Ctrl_PT2000_Enable_mode_Return
 *  Rte_Runnable_CtPT2000_Handler_PoPT2000_Ctrl_PT2000_Enable_mode_Start
 *  Rte_Runnable_CtPT2000_Handler_PoPT2000_Ctrl_PT2000_Init_Return
 *  Rte_Runnable_CtPT2000_Handler_PoPT2000_Ctrl_PT2000_Init_Start
 *  Rte_Runnable_CtPT2000_Handler_PoPT2000_Ctrl_PT2000_Mode_Change_Return
 *  Rte_Runnable_CtPT2000_Handler_PoPT2000_Ctrl_PT2000_Mode_Change_Start
 *  Rte_Runnable_CtPT2000_Handler_PoPT2000_Ctrl_Set_ConstantCurrent_Return
 *  Rte_Runnable_CtPT2000_Handler_PoPT2000_Ctrl_Set_ConstantCurrent_Start
 *  Rte_Runnable_CtPT2000_Handler_PoPT2000_Ctrl_Set_Peak_Hold_Return
 *  Rte_Runnable_CtPT2000_Handler_PoPT2000_Ctrl_Set_Peak_Hold_Start
 *  Rte_Runnable_CtPWM_Handler_PWM_SET_Return
 *  Rte_Runnable_CtPWM_Handler_PWM_SET_Start
 *  Rte_Runnable_Det_ReportError_Return
 *  Rte_Runnable_Det_ReportError_Start
 *  Rte_Runnable_EcuM_EcuM_MainFunction_Return
 *  Rte_Runnable_EcuM_EcuM_MainFunction_Start
 *  Rte_Runnable_EcuM_GetBootTarget_Return
 *  Rte_Runnable_EcuM_GetBootTarget_Start
 *  Rte_Runnable_EcuM_GetLastShutdownTarget_Return
 *  Rte_Runnable_EcuM_GetLastShutdownTarget_Start
 *  Rte_Runnable_EcuM_GetShutdownCause_Return
 *  Rte_Runnable_EcuM_GetShutdownCause_Start
 *  Rte_Runnable_EcuM_GetShutdownTarget_Return
 *  Rte_Runnable_EcuM_GetShutdownTarget_Start
 *  Rte_Runnable_EcuM_SelectBootTarget_Return
 *  Rte_Runnable_EcuM_SelectBootTarget_Start
 *  Rte_Runnable_EcuM_SelectShutdownCause_Return
 *  Rte_Runnable_EcuM_SelectShutdownCause_Start
 *  Rte_Runnable_EcuM_SelectShutdownTarget_Return
 *  Rte_Runnable_EcuM_SelectShutdownTarget_Start
 *  Rte_Runnable_Os_OsCore0_swc_GetCounterValue_Return
 *  Rte_Runnable_Os_OsCore0_swc_GetCounterValue_Start
 *  Rte_Runnable_Os_OsCore0_swc_GetElapsedValue_Return
 *  Rte_Runnable_Os_OsCore0_swc_GetElapsedValue_Start
 *  Rte_Runnable_Os_OsCore1_swc_GetCounterValue_Return
 *  Rte_Runnable_Os_OsCore1_swc_GetCounterValue_Start
 *  Rte_Runnable_Os_OsCore1_swc_GetElapsedValue_Return
 *  Rte_Runnable_Os_OsCore1_swc_GetElapsedValue_Start
 *  Rte_Runnable_Os_OsCore2_swc_GetCounterValue_Return
 *  Rte_Runnable_Os_OsCore2_swc_GetCounterValue_Start
 *  Rte_Runnable_Os_OsCore2_swc_GetElapsedValue_Return
 *  Rte_Runnable_Os_OsCore2_swc_GetElapsedValue_Start
 *  Rte_Runnable_Os_OsCore3_swc_GetCounterValue_Return
 *  Rte_Runnable_Os_OsCore3_swc_GetCounterValue_Start
 *  Rte_Runnable_Os_OsCore3_swc_GetElapsedValue_Return
 *  Rte_Runnable_Os_OsCore3_swc_GetElapsedValue_Start
 *  Rte_Runnable_Os_OsCore4_swc_GetCounterValue_Return
 *  Rte_Runnable_Os_OsCore4_swc_GetCounterValue_Start
 *  Rte_Runnable_Os_OsCore4_swc_GetElapsedValue_Return
 *  Rte_Runnable_Os_OsCore4_swc_GetElapsedValue_Start
 *  Rte_Runnable_Os_OsCore5_swc_GetCounterValue_Return
 *  Rte_Runnable_Os_OsCore5_swc_GetCounterValue_Start
 *  Rte_Runnable_Os_OsCore5_swc_GetElapsedValue_Return
 *  Rte_Runnable_Os_OsCore5_swc_GetElapsedValue_Start
 *  Rte_SwitchHook_BswM_Switch_ESH_ModeSwitch_BswM_MDGP_ESH_Mode_Return
 *  Rte_SwitchHook_BswM_Switch_ESH_ModeSwitch_BswM_MDGP_ESH_Mode_Start
 *  Rte_Task_Activate
 *  Rte_Task_Dispatch
 *  Rte_Task_WaitEvent
 *  Rte_Task_WaitEventRet
 *  Rte_WriteHook_CtIoHardWare_PpIMU_IMUAcc_Return
 *  Rte_WriteHook_CtIoHardWare_PpIMU_IMUAcc_Start
 *  Rte_WriteHook_CtIoHardWare_PpIMU_IMUAngle_Return
 *  Rte_WriteHook_CtIoHardWare_PpIMU_IMUAngle_Start
 *  Rte_WriteHook_CtIoHardWare_PpIMU_IMURate_Return
 *  Rte_WriteHook_CtIoHardWare_PpIMU_IMURate_Start
 *  Rte_WriteHook_CtIoHardWare_PpIMU_IMUVel_Return
 *  Rte_WriteHook_CtIoHardWare_PpIMU_IMUVel_Start
 *  Rte_WriteHook_CtIoHardWare_PpPedlPos_PedlPos_Return
 *  Rte_WriteHook_CtIoHardWare_PpPedlPos_PedlPos_Start
 *  Rte_WriteHook_CtIoHardWare_PpPressure_Pressure_Return
 *  Rte_WriteHook_CtIoHardWare_PpPressure_Pressure_Start
 *  Rte_WriteHook_CtIoHardWare_PpSteerWhl_SteerWhl_Return
 *  Rte_WriteHook_CtIoHardWare_PpSteerWhl_SteerWhl_Start
 *  Rte_WriteHook_CtIoHardWare_PpSuspHeight_SuspHeight_Return
 *  Rte_WriteHook_CtIoHardWare_PpSuspHeight_SuspHeight_Start
 *  Rte_WriteHook_CtMDA_Control_Logic_PpMotTgtOutFL_MotTgtOutFL_Return
 *  Rte_WriteHook_CtMDA_Control_Logic_PpMotTgtOutFL_MotTgtOutFL_Start
 *  Rte_WriteHook_CtMDA_Control_Logic_PpMotTgtOutFR_MotTgtOutFR_Return
 *  Rte_WriteHook_CtMDA_Control_Logic_PpMotTgtOutFR_MotTgtOutFR_Start
 *  Rte_WriteHook_CtMDA_Control_Logic_PpMotTgtOutRL_MotTgtOutRL_Return
 *  Rte_WriteHook_CtMDA_Control_Logic_PpMotTgtOutRL_MotTgtOutRL_Start
 *  Rte_WriteHook_CtMDA_Control_Logic_PpMotTgtOutRR_MotTgtOutRR_Return
 *  Rte_WriteHook_CtMDA_Control_Logic_PpMotTgtOutRR_MotTgtOutRR_Start
 *  Rte_WriteHook_CtMDA_Control_Logic_PpVlvTgtCCFF_VlvTgtChannel_Return
 *  Rte_WriteHook_CtMDA_Control_Logic_PpVlvTgtCCFF_VlvTgtChannel_Start
 *  Rte_WriteHook_CtMDA_Control_Logic_PpVlvTgtCCFF_VlvTgtCurrent_Return
 *  Rte_WriteHook_CtMDA_Control_Logic_PpVlvTgtCCFF_VlvTgtCurrent_Start
 *  Rte_WriteHook_CtMDA_Control_Logic_PpVlvTgtCCFF_VlvTgtFlutter_Return
 *  Rte_WriteHook_CtMDA_Control_Logic_PpVlvTgtCCFF_VlvTgtFlutter_Start
 *  Rte_WriteHook_CtMDA_Control_Logic_PpVlvTgtCCFF_VlvTgtFrequency_Return
 *  Rte_WriteHook_CtMDA_Control_Logic_PpVlvTgtCCFF_VlvTgtFrequency_Start
 *  Rte_WriteHook_CtMotor_FL_PpMotFLAct_MotFLAct_Return
 *  Rte_WriteHook_CtMotor_FL_PpMotFLAct_MotFLAct_Start
 *  Rte_WriteHook_CtMotor_FR_PpMotFRAct_MotFRAct_Return
 *  Rte_WriteHook_CtMotor_FR_PpMotFRAct_MotFRAct_Start
 *  Rte_WriteHook_CtMotor_RL_PpMotRLAct_MotRLAct_Return
 *  Rte_WriteHook_CtMotor_RL_PpMotRLAct_MotRLAct_Start
 *  Rte_WriteHook_CtMotor_RR_PpMotRRAct_MotRRAct_Return
 *  Rte_WriteHook_CtMotor_RR_PpMotRRAct_MotRRAct_Start
 *  Rte_WriteHook_CtPSI5_Handler_PpBodyAccZ_BodyAcc_Return
 *  Rte_WriteHook_CtPSI5_Handler_PpBodyAccZ_BodyAcc_Start
 *  Rte_WriteHook_CtPSI5_Handler_PpWhlAccZ_WhlAcc_Return
 *  Rte_WriteHook_CtPSI5_Handler_PpWhlAccZ_WhlAcc_Start
 *  Rte_WriteHook_CtPT2000_Handler_PpVelFbAll_VlvFL_Return
 *  Rte_WriteHook_CtPT2000_Handler_PpVelFbAll_VlvFL_Start
 *  Rte_WriteHook_CtPT2000_Handler_PpVelFbAll_VlvFR_Return
 *  Rte_WriteHook_CtPT2000_Handler_PpVelFbAll_VlvFR_Start
 *  Rte_WriteHook_CtPT2000_Handler_PpVelFbAll_VlvRL_Return
 *  Rte_WriteHook_CtPT2000_Handler_PpVelFbAll_VlvRL_Start
 *  Rte_WriteHook_CtPT2000_Handler_PpVelFbAll_VlvRR_Return
 *  Rte_WriteHook_CtPT2000_Handler_PpVelFbAll_VlvRR_Start
 *  SchM_EnterHook_Adc_KernelData_Return
 *  SchM_EnterHook_Adc_KernelData_Start
 *  SchM_EnterHook_Adc_SrcRegAccess_Return
 *  SchM_EnterHook_Adc_SrcRegAccess_Start
 *  SchM_EnterHook_BswM_BSWM_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_BswM_BSWM_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_1_Return
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_1_Start
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_2_Return
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_2_Start
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_3_Return
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_3_Start
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_4_Return
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_4_Start
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_5_Return
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_5_Start
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_6_Return
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_6_Start
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_7_Return
 *  SchM_EnterHook_CanIf_CANIF_EXCLUSIVE_AREA_7_Start
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_1_Return
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_1_Start
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_2_Return
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_2_Start
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_3_Return
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_3_Start
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_4_Return
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_4_Start
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_5_Return
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_5_Start
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_6_Return
 *  SchM_EnterHook_CanSM_CANSM_EXCLUSIVE_AREA_6_Start
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_1_Return
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_1_Start
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_2_Return
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_2_Start
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_3_Return
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_3_Start
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_4_Return
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_4_Start
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_5_Return
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_5_Start
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_6_Return
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_6_Start
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_7_Return
 *  SchM_EnterHook_Can_CAN_EXCLUSIVE_AREA_7_Start
 *  SchM_EnterHook_ComM_COMM_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_ComM_COMM_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_ComM_COMM_EXCLUSIVE_AREA_1_Return
 *  SchM_EnterHook_ComM_COMM_EXCLUSIVE_AREA_1_Start
 *  SchM_EnterHook_Com_COM_EXCLUSIVE_AREA_BOTH_Return
 *  SchM_EnterHook_Com_COM_EXCLUSIVE_AREA_BOTH_Start
 *  SchM_EnterHook_Com_COM_EXCLUSIVE_AREA_RX_Return
 *  SchM_EnterHook_Com_COM_EXCLUSIVE_AREA_RX_Start
 *  SchM_EnterHook_Com_COM_EXCLUSIVE_AREA_TX_Return
 *  SchM_EnterHook_Com_COM_EXCLUSIVE_AREA_TX_Start
 *  SchM_EnterHook_Det_DET_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_Det_DET_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_Dma_ChEventStatus_Return
 *  SchM_EnterHook_Dma_ChEventStatus_Start
 *  SchM_EnterHook_Dma_ChannelConfigUpdate_Return
 *  SchM_EnterHook_Dma_ChannelConfigUpdate_Start
 *  SchM_EnterHook_Dma_ChannelFreezeResume_Return
 *  SchM_EnterHook_Dma_ChannelFreezeResume_Start
 *  SchM_EnterHook_Dma_ChannelHWTrigger_Return
 *  SchM_EnterHook_Dma_ChannelHWTrigger_Start
 *  SchM_EnterHook_Dma_ChannelInitDeinit_Return
 *  SchM_EnterHook_Dma_ChannelInitDeinit_Start
 *  SchM_EnterHook_Dma_ChannelStartStop_Return
 *  SchM_EnterHook_Dma_ChannelStartStop_Start
 *  SchM_EnterHook_Dma_ChannelSwitchBuffer_Return
 *  SchM_EnterHook_Dma_ChannelSwitchBuffer_Start
 *  SchM_EnterHook_Dma_InterruptStatus_Return
 *  SchM_EnterHook_Dma_InterruptStatus_Start
 *  SchM_EnterHook_Dma_MEErrorStatus_Return
 *  SchM_EnterHook_Dma_MEErrorStatus_Start
 *  SchM_EnterHook_EcuM_ECUM_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_EcuM_ECUM_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_EcuM_ECUM_EXCLUSIVE_AREA_1_Return
 *  SchM_EnterHook_EcuM_ECUM_EXCLUSIVE_AREA_1_Start
 *  SchM_EnterHook_EcuM_ECUM_EXCLUSIVE_AREA_2_Return
 *  SchM_EnterHook_EcuM_ECUM_EXCLUSIVE_AREA_2_Start
 *  SchM_EnterHook_Gpt_Get100UsPredefTimerValue_Return
 *  SchM_EnterHook_Gpt_Get100UsPredefTimerValue_Start
 *  SchM_EnterHook_Gpt_Get1UsPredefTimerValue_Return
 *  SchM_EnterHook_Gpt_Get1UsPredefTimerValue_Start
 *  SchM_EnterHook_Icu_17_TimerIp_CcuInterruptHandle_Return
 *  SchM_EnterHook_Icu_17_TimerIp_CcuInterruptHandle_Start
 *  SchM_EnterHook_Icu_17_TimerIp_CcuVariableupdate_Return
 *  SchM_EnterHook_Icu_17_TimerIp_CcuVariableupdate_Start
 *  SchM_EnterHook_Icu_17_TimerIp_EnableNotification_Return
 *  SchM_EnterHook_Icu_17_TimerIp_EnableNotification_Start
 *  SchM_EnterHook_Icu_17_TimerIp_EnableWakeup_Return
 *  SchM_EnterHook_Icu_17_TimerIp_EnableWakeup_Start
 *  SchM_EnterHook_Icu_17_TimerIp_GtmEnableEdgeCount_Return
 *  SchM_EnterHook_Icu_17_TimerIp_GtmEnableEdgeCount_Start
 *  SchM_EnterHook_Icu_17_TimerIp_GtmGetDutyCycle_Return
 *  SchM_EnterHook_Icu_17_TimerIp_GtmGetDutyCycle_Start
 *  SchM_EnterHook_Icu_17_TimerIp_ResetEdgeCount_Return
 *  SchM_EnterHook_Icu_17_TimerIp_ResetEdgeCount_Start
 *  SchM_EnterHook_Icu_17_TimerIp_SetActivationCondition_Return
 *  SchM_EnterHook_Icu_17_TimerIp_SetActivationCondition_Start
 *  SchM_EnterHook_McalLib_CpuEndInit_Return
 *  SchM_EnterHook_McalLib_CpuEndInit_Start
 *  SchM_EnterHook_McalLib_PeripheralEndInit_Return
 *  SchM_EnterHook_McalLib_PeripheralEndInit_Start
 *  SchM_EnterHook_McalLib_SafetyEndInit_Return
 *  SchM_EnterHook_McalLib_SafetyEndInit_Start
 *  SchM_EnterHook_McalLib_StmTimerResolution_Return
 *  SchM_EnterHook_McalLib_StmTimerResolution_Start
 *  SchM_EnterHook_Mcu_AtomAgcReg_Return
 *  SchM_EnterHook_Mcu_AtomAgcReg_Start
 *  SchM_EnterHook_Mcu_TomTgcReg_Return
 *  SchM_EnterHook_Mcu_TomTgcReg_Start
 *  SchM_EnterHook_PduR_PDUR_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_PduR_PDUR_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_Pwm_17_GtmCcu6_HandleNotification_Return
 *  SchM_EnterHook_Pwm_17_GtmCcu6_HandleNotification_Start
 *  SchM_EnterHook_Pwm_17_GtmCcu6_PeriodAndDutyUpdate_Return
 *  SchM_EnterHook_Pwm_17_GtmCcu6_PeriodAndDutyUpdate_Start
 *  SchM_EnterHook_Spi_Buffer_Update_Return
 *  SchM_EnterHook_Spi_Buffer_Update_Start
 *  SchM_EnterHook_Spi_Cancel_Seq_Return
 *  SchM_EnterHook_Spi_Cancel_Seq_Start
 *  SchM_EnterHook_Spi_ChannelLock_Return
 *  SchM_EnterHook_Spi_ChannelLock_Start
 *  SchM_EnterHook_Spi_Queue_Update_QSPI0_Return
 *  SchM_EnterHook_Spi_Queue_Update_QSPI0_Start
 *  SchM_EnterHook_Spi_Queue_Update_QSPI1_Return
 *  SchM_EnterHook_Spi_Queue_Update_QSPI1_Start
 *  SchM_EnterHook_Spi_Queue_Update_QSPI2_Return
 *  SchM_EnterHook_Spi_Queue_Update_QSPI2_Start
 *  SchM_EnterHook_Spi_Queue_Update_QSPI3_Return
 *  SchM_EnterHook_Spi_Queue_Update_QSPI3_Start
 *  SchM_EnterHook_Spi_Queue_Update_QSPI4_Return
 *  SchM_EnterHook_Spi_Queue_Update_QSPI4_Start
 *  SchM_EnterHook_Spi_Queue_Update_QSPI5_Return
 *  SchM_EnterHook_Spi_Queue_Update_QSPI5_Start
 *  SchM_EnterHook_Spi_Queue_Update_Return
 *  SchM_EnterHook_Spi_Queue_Update_Start
 *  SchM_EnterHook_Spi_SyncLock_Return
 *  SchM_EnterHook_Spi_SyncLock_Start
 *  SchM_EnterHook_Xcp_CANXCP_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_Xcp_CANXCP_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_Xcp_FRXCP_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_Xcp_FRXCP_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_Xcp_FRXCP_EXCLUSIVE_AREA_1_Return
 *  SchM_EnterHook_Xcp_FRXCP_EXCLUSIVE_AREA_1_Start
 *  SchM_EnterHook_Xcp_FRXCP_EXCLUSIVE_AREA_2_Return
 *  SchM_EnterHook_Xcp_FRXCP_EXCLUSIVE_AREA_2_Start
 *  SchM_EnterHook_Xcp_TCPIPXCP_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_Xcp_TCPIPXCP_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_Xcp_XCP_EXCLUSIVE_AREA_0_Return
 *  SchM_EnterHook_Xcp_XCP_EXCLUSIVE_AREA_0_Start
 *  SchM_EnterHook_Xcp_XCP_EXCLUSIVE_AREA_1_Return
 *  SchM_EnterHook_Xcp_XCP_EXCLUSIVE_AREA_1_Start
 *  SchM_EnterHook_Xcp_XCP_EXCLUSIVE_AREA_2_Return
 *  SchM_EnterHook_Xcp_XCP_EXCLUSIVE_AREA_2_Start
 *  SchM_ExitHook_Adc_KernelData_Return
 *  SchM_ExitHook_Adc_KernelData_Start
 *  SchM_ExitHook_Adc_SrcRegAccess_Return
 *  SchM_ExitHook_Adc_SrcRegAccess_Start
 *  SchM_ExitHook_BswM_BSWM_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_BswM_BSWM_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_1_Return
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_1_Start
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_2_Return
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_2_Start
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_3_Return
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_3_Start
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_4_Return
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_4_Start
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_5_Return
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_5_Start
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_6_Return
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_6_Start
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_7_Return
 *  SchM_ExitHook_CanIf_CANIF_EXCLUSIVE_AREA_7_Start
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_1_Return
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_1_Start
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_2_Return
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_2_Start
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_3_Return
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_3_Start
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_4_Return
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_4_Start
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_5_Return
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_5_Start
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_6_Return
 *  SchM_ExitHook_CanSM_CANSM_EXCLUSIVE_AREA_6_Start
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_1_Return
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_1_Start
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_2_Return
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_2_Start
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_3_Return
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_3_Start
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_4_Return
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_4_Start
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_5_Return
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_5_Start
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_6_Return
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_6_Start
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_7_Return
 *  SchM_ExitHook_Can_CAN_EXCLUSIVE_AREA_7_Start
 *  SchM_ExitHook_ComM_COMM_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_ComM_COMM_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_ComM_COMM_EXCLUSIVE_AREA_1_Return
 *  SchM_ExitHook_ComM_COMM_EXCLUSIVE_AREA_1_Start
 *  SchM_ExitHook_Com_COM_EXCLUSIVE_AREA_BOTH_Return
 *  SchM_ExitHook_Com_COM_EXCLUSIVE_AREA_BOTH_Start
 *  SchM_ExitHook_Com_COM_EXCLUSIVE_AREA_RX_Return
 *  SchM_ExitHook_Com_COM_EXCLUSIVE_AREA_RX_Start
 *  SchM_ExitHook_Com_COM_EXCLUSIVE_AREA_TX_Return
 *  SchM_ExitHook_Com_COM_EXCLUSIVE_AREA_TX_Start
 *  SchM_ExitHook_Det_DET_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_Det_DET_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_Dma_ChEventStatus_Return
 *  SchM_ExitHook_Dma_ChEventStatus_Start
 *  SchM_ExitHook_Dma_ChannelConfigUpdate_Return
 *  SchM_ExitHook_Dma_ChannelConfigUpdate_Start
 *  SchM_ExitHook_Dma_ChannelFreezeResume_Return
 *  SchM_ExitHook_Dma_ChannelFreezeResume_Start
 *  SchM_ExitHook_Dma_ChannelHWTrigger_Return
 *  SchM_ExitHook_Dma_ChannelHWTrigger_Start
 *  SchM_ExitHook_Dma_ChannelInitDeinit_Return
 *  SchM_ExitHook_Dma_ChannelInitDeinit_Start
 *  SchM_ExitHook_Dma_ChannelStartStop_Return
 *  SchM_ExitHook_Dma_ChannelStartStop_Start
 *  SchM_ExitHook_Dma_ChannelSwitchBuffer_Return
 *  SchM_ExitHook_Dma_ChannelSwitchBuffer_Start
 *  SchM_ExitHook_Dma_InterruptStatus_Return
 *  SchM_ExitHook_Dma_InterruptStatus_Start
 *  SchM_ExitHook_Dma_MEErrorStatus_Return
 *  SchM_ExitHook_Dma_MEErrorStatus_Start
 *  SchM_ExitHook_EcuM_ECUM_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_EcuM_ECUM_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_EcuM_ECUM_EXCLUSIVE_AREA_1_Return
 *  SchM_ExitHook_EcuM_ECUM_EXCLUSIVE_AREA_1_Start
 *  SchM_ExitHook_EcuM_ECUM_EXCLUSIVE_AREA_2_Return
 *  SchM_ExitHook_EcuM_ECUM_EXCLUSIVE_AREA_2_Start
 *  SchM_ExitHook_Gpt_Get100UsPredefTimerValue_Return
 *  SchM_ExitHook_Gpt_Get100UsPredefTimerValue_Start
 *  SchM_ExitHook_Gpt_Get1UsPredefTimerValue_Return
 *  SchM_ExitHook_Gpt_Get1UsPredefTimerValue_Start
 *  SchM_ExitHook_Icu_17_TimerIp_CcuInterruptHandle_Return
 *  SchM_ExitHook_Icu_17_TimerIp_CcuInterruptHandle_Start
 *  SchM_ExitHook_Icu_17_TimerIp_CcuVariableupdate_Return
 *  SchM_ExitHook_Icu_17_TimerIp_CcuVariableupdate_Start
 *  SchM_ExitHook_Icu_17_TimerIp_EnableNotification_Return
 *  SchM_ExitHook_Icu_17_TimerIp_EnableNotification_Start
 *  SchM_ExitHook_Icu_17_TimerIp_EnableWakeup_Return
 *  SchM_ExitHook_Icu_17_TimerIp_EnableWakeup_Start
 *  SchM_ExitHook_Icu_17_TimerIp_GtmEnableEdgeCount_Return
 *  SchM_ExitHook_Icu_17_TimerIp_GtmEnableEdgeCount_Start
 *  SchM_ExitHook_Icu_17_TimerIp_GtmGetDutyCycle_Return
 *  SchM_ExitHook_Icu_17_TimerIp_GtmGetDutyCycle_Start
 *  SchM_ExitHook_Icu_17_TimerIp_ResetEdgeCount_Return
 *  SchM_ExitHook_Icu_17_TimerIp_ResetEdgeCount_Start
 *  SchM_ExitHook_Icu_17_TimerIp_SetActivationCondition_Return
 *  SchM_ExitHook_Icu_17_TimerIp_SetActivationCondition_Start
 *  SchM_ExitHook_McalLib_CpuEndInit_Return
 *  SchM_ExitHook_McalLib_CpuEndInit_Start
 *  SchM_ExitHook_McalLib_PeripheralEndInit_Return
 *  SchM_ExitHook_McalLib_PeripheralEndInit_Start
 *  SchM_ExitHook_McalLib_SafetyEndInit_Return
 *  SchM_ExitHook_McalLib_SafetyEndInit_Start
 *  SchM_ExitHook_McalLib_StmTimerResolution_Return
 *  SchM_ExitHook_McalLib_StmTimerResolution_Start
 *  SchM_ExitHook_Mcu_AtomAgcReg_Return
 *  SchM_ExitHook_Mcu_AtomAgcReg_Start
 *  SchM_ExitHook_Mcu_TomTgcReg_Return
 *  SchM_ExitHook_Mcu_TomTgcReg_Start
 *  SchM_ExitHook_PduR_PDUR_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_PduR_PDUR_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_Pwm_17_GtmCcu6_HandleNotification_Return
 *  SchM_ExitHook_Pwm_17_GtmCcu6_HandleNotification_Start
 *  SchM_ExitHook_Pwm_17_GtmCcu6_PeriodAndDutyUpdate_Return
 *  SchM_ExitHook_Pwm_17_GtmCcu6_PeriodAndDutyUpdate_Start
 *  SchM_ExitHook_Spi_Buffer_Update_Return
 *  SchM_ExitHook_Spi_Buffer_Update_Start
 *  SchM_ExitHook_Spi_Cancel_Seq_Return
 *  SchM_ExitHook_Spi_Cancel_Seq_Start
 *  SchM_ExitHook_Spi_ChannelLock_Return
 *  SchM_ExitHook_Spi_ChannelLock_Start
 *  SchM_ExitHook_Spi_Queue_Update_QSPI0_Return
 *  SchM_ExitHook_Spi_Queue_Update_QSPI0_Start
 *  SchM_ExitHook_Spi_Queue_Update_QSPI1_Return
 *  SchM_ExitHook_Spi_Queue_Update_QSPI1_Start
 *  SchM_ExitHook_Spi_Queue_Update_QSPI2_Return
 *  SchM_ExitHook_Spi_Queue_Update_QSPI2_Start
 *  SchM_ExitHook_Spi_Queue_Update_QSPI3_Return
 *  SchM_ExitHook_Spi_Queue_Update_QSPI3_Start
 *  SchM_ExitHook_Spi_Queue_Update_QSPI4_Return
 *  SchM_ExitHook_Spi_Queue_Update_QSPI4_Start
 *  SchM_ExitHook_Spi_Queue_Update_QSPI5_Return
 *  SchM_ExitHook_Spi_Queue_Update_QSPI5_Start
 *  SchM_ExitHook_Spi_Queue_Update_Return
 *  SchM_ExitHook_Spi_Queue_Update_Start
 *  SchM_ExitHook_Spi_SyncLock_Return
 *  SchM_ExitHook_Spi_SyncLock_Start
 *  SchM_ExitHook_Xcp_CANXCP_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_Xcp_CANXCP_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_Xcp_FRXCP_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_Xcp_FRXCP_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_Xcp_FRXCP_EXCLUSIVE_AREA_1_Return
 *  SchM_ExitHook_Xcp_FRXCP_EXCLUSIVE_AREA_1_Start
 *  SchM_ExitHook_Xcp_FRXCP_EXCLUSIVE_AREA_2_Return
 *  SchM_ExitHook_Xcp_FRXCP_EXCLUSIVE_AREA_2_Start
 *  SchM_ExitHook_Xcp_TCPIPXCP_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_Xcp_TCPIPXCP_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_Xcp_XCP_EXCLUSIVE_AREA_0_Return
 *  SchM_ExitHook_Xcp_XCP_EXCLUSIVE_AREA_0_Start
 *  SchM_ExitHook_Xcp_XCP_EXCLUSIVE_AREA_1_Return
 *  SchM_ExitHook_Xcp_XCP_EXCLUSIVE_AREA_1_Start
 *  SchM_ExitHook_Xcp_XCP_EXCLUSIVE_AREA_2_Return
 *  SchM_ExitHook_Xcp_XCP_EXCLUSIVE_AREA_2_Start
 *  SchM_Schedulable_BswM_BswM_MainFunction_Return
 *  SchM_Schedulable_BswM_BswM_MainFunction_Start
 *  SchM_Schedulable_CanSM_CanSM_MainFunction_Return
 *  SchM_Schedulable_CanSM_CanSM_MainFunction_Start
 *  SchM_Schedulable_Can_Can_MainFunction_BusOff_Return
 *  SchM_Schedulable_Can_Can_MainFunction_BusOff_Start
 *  SchM_Schedulable_Can_Can_MainFunction_Mode_Return
 *  SchM_Schedulable_Can_Can_MainFunction_Mode_Start
 *  SchM_Schedulable_Can_Can_MainFunction_Wakeup_Return
 *  SchM_Schedulable_Can_Can_MainFunction_Wakeup_Start
 *  SchM_Schedulable_ComM_ComM_MainFunction_0_Return
 *  SchM_Schedulable_ComM_ComM_MainFunction_0_Start
 *  SchM_Schedulable_ComM_ComM_MainFunction_1_Return
 *  SchM_Schedulable_ComM_ComM_MainFunction_1_Start
 *  SchM_Schedulable_ComM_ComM_MainFunction_2_Return
 *  SchM_Schedulable_ComM_ComM_MainFunction_2_Start
 *  SchM_Schedulable_ComM_ComM_MainFunction_3_Return
 *  SchM_Schedulable_ComM_ComM_MainFunction_3_Start
 *  SchM_Schedulable_ComM_ComM_MainFunction_4_Return
 *  SchM_Schedulable_ComM_ComM_MainFunction_4_Start
 *  SchM_Schedulable_ComM_ComM_MainFunction_5_Return
 *  SchM_Schedulable_ComM_ComM_MainFunction_5_Start
 *  SchM_Schedulable_Com_Com_MainFunctionRx_Return
 *  SchM_Schedulable_Com_Com_MainFunctionRx_Start
 *  SchM_Schedulable_Com_Com_MainFunctionTx_Return
 *  SchM_Schedulable_Com_Com_MainFunctionTx_Start
 *  SchM_Schedulable_EcuM_EcuM_MainFunction_Return
 *  SchM_Schedulable_EcuM_EcuM_MainFunction_Start
 *  SchM_Schedulable_Rte_Rte_ComSendSignalProxyPeriodic_Return
 *  SchM_Schedulable_Rte_Rte_ComSendSignalProxyPeriodic_Start
 *  SchM_Schedulable_Spi_Spi_MainFunction_Handling_Return
 *  SchM_Schedulable_Spi_Spi_MainFunction_Handling_Start
 *  SchM_Schedulable_Xcp_CanXcp_MainFunction_Return
 *  SchM_Schedulable_Xcp_CanXcp_MainFunction_Start
 *  SchM_Schedulable_Xcp_Xcp_MainFunction_Return
 *  SchM_Schedulable_Xcp_Xcp_MainFunction_Start
 *
 *********************************************************************************************************************/

/* double include prevention */
#ifndef _RTE_HOOK_H
# define _RTE_HOOK_H

# include "Os.h" /* PRQA S 0828, 0883 */ /* MD_MSR_1.1_828, MD_Rte_Os */

# include "Rte_Type.h"
# include "Rte_Cfg.h"

# ifndef RTE_VFB_TRACE
#  define RTE_VFB_TRACE (0)
# endif

#endif /* _RTE_HOOK_H */

/**********************************************************************************************************************
 MISRA 2004 violations and justifications
 *********************************************************************************************************************/

/* module specific MISRA deviations:
   MD_Rte_Os:
     Reason:     This justification is used as summary justification for all deviations caused by the MICROSAR OS
                 which is for testing of the RTE. Those deviations are no issues in the RTE code.
     Risk:       No functional risk.
     Prevention: Not required.

*/
